# Evaluation

In [1]:
import os

os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"

import random
from collections import Counter
import json
from tqdm import tqdm
import editdistance
import numpy as np

from transformers import AutoTokenizer, BertForMaskedLM, BertTokenizer, BertConfig
from transformers import LineByLineTextDataset, DataCollatorForLanguageModeling
from transformers import Trainer, TrainingArguments
from transformers import pipeline

import torch

/data01/alocaputo/miniconda3/envs/deepmind/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
test_set = json.load(open('data/archaic/test_common.json'))
max_l = max([ len(x['masked_gt']) for x in test_set])

dialects = ['atticionic', 'doric', 'northwest', 'aeolic']

### Utils

In [3]:
# Copyright 2021 the Ithaca Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Example for running inference. See also colab."""

import functools
import pickle

from absl import app
from absl import flags
from ithaca.eval import inference
from ithaca.models.model import Model
from ithaca.util.alphabet import GreekAlphabet
import jax

In [4]:
def load_checkpoint(path):
  """Loads a checkpoint pickle.

  Args:
    path: path to checkpoint pickle

  Returns:
    a model config dictionary (arguments to the model's constructor), a dict of
    dicts containing region mapping information, a GreekAlphabet instance with
    indices and words populated from the checkpoint, a dict of Jax arrays
    `params`, and a `forward` function.
  """

  # Pickled checkpoint dict containing params and various config:
  with open(path, 'rb') as f:
    checkpoint = pickle.load(f)

  # We reconstruct the model using the same arguments as during training, which
  # are saved as a dict in the "model_config" key, and construct a `forward`
  # function of the form required by attribute() and restore().
  params = jax.device_put(checkpoint['params'])
  model = Model(**checkpoint['model_config'])
  forward = functools.partial(model.apply, params)

  # Contains the mapping between region IDs and names:
  region_map = checkpoint['region_map']

  # Use vocabulary mapping from the checkpoint, the rest of the values in the
  # class are fixed and constant e.g. the padding symbol
  alphabet = GreekAlphabet()
  alphabet.idx2word = checkpoint['alphabet']['idx2word']
  alphabet.word2idx = checkpoint['alphabet']['word2idx']

  return checkpoint['model_config'], region_map, alphabet, params, forward

## Base models

**Ithaca base**

In [29]:
!python3 run_ithaca_inference.py --results_path results/archaic/ithaca --cuda 0

/data01/alocaputo/miniconda3/envs/ancientGPT/lib/python3.9/pty.py:85: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid, fd = os.forkpty()
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

100%|███████████████████████████████████████████| 95/95 [01:24<00:00,  1.13it/s]

In [30]:
os.makedirs('results/archaic/ithaca', exist_ok=True)

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc1 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}

for inscription in test_set:

    ground_truth = inscription['text'].strip()
    text_masked = inscription['masked_ithaca']
    phi_id = inscription['id']

    dialect = inscription['dialect']

    predictions = json.load(open(f'results/archaic/ithaca/{phi_id}.json'))['predictions']

    text_predictions = [ pred['text'] for pred in predictions]

    assert len(text_predictions[0]) == len(ground_truth)
    ctop1 = 0
    ctop20 = 0
    if ground_truth in text_predictions[:1]:
        ctop1 = 1
        ctop20 = 1
    if ground_truth in text_predictions:
        ctop20 = 1

    l = text_masked.count('?')

    acc1[dialect][l].append(ctop1)
    acc20[dialect][l].append(ctop20)

    editd[dialect][l].append(editdistance.eval(text_predictions[0], ground_truth) / l)

for dialect in dialects:
    print(f"======== {dialect} ========")
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
    print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')
    print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')

print(f"======== TOTAL ========")
cert = { x: [] for x in range(1, max_l+1)}
for k, vs in editd.items():
    for kk, v in vs.items():
        cert[kk].extend(v)
acc1t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc1.items():
    for kk, v in vs.items():
        acc1t[kk].extend(v)

acc20t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc20.items():
    for kk, v in vs.items():
        acc20t[kk].extend(v)
print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

======== atticionic ========
ACC1 : 28.15%
ACC20: 45.18%
CER  : 65.16%
======== doric ========
ACC1 : 25.00%
ACC20: 56.67%
CER  : 60.45%
======== northwest ========
ACC1 : 40.00%
ACC20: 70.00%
CER  : 50.83%
======== aeolic ========
ACC1 : 33.33%
ACC20: 33.33%
CER  : 66.67%
======== TOTAL ========
CER : 67.11%
ACC1 : 24.24%
ACC20 : 42.66%

**AG BERT**

In [ ]:
model_name = "pranaydeeps/Ancient-Greek-BERT"
fill_mask = pipeline("fill-mask", model=model_name, tokenizer=model_name, top_k=3500)

ctop1s = []
ctop20s = []

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc1 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
for sentence in tqdm(test_set):

    masked = sentence['masked_ag']
    ground_truth = sentence['masked_gt']

    dialect = sentence['dialect']

    inference_result = fill_mask(masked)

    constr = [ x for x in inference_result if len(x['token_str']) == len(ground_truth)][:20]

    ctop1 = 0
    ctop20 = 0
    if ground_truth in [ x['token_str'] for x in constr[:1] ]:
        ctop20 = 1
        ctop1 = 1
    if ground_truth in [ x['token_str'] for x in constr ]:
        ctop20 = 1

    ctop1s.append(ctop1)
    ctop20s.append(ctop20)

    acc1[dialect][len(ground_truth)].append(ctop1)
    acc20[dialect][len(ground_truth)].append(ctop20)

    if constr != []:
        editd[dialect][len(ground_truth)].append(editdistance.eval(constr[0]['token_str'], ground_truth) / len(ground_truth))
    else:
        editd[dialect][len(ground_truth)].append(1.0)

for dialect in dialects:
    print(f"======== {dialect} ========")
    print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
    print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')

print(f"======== TOTAL ========")
cert = { x: [] for x in range(1, max_l+1)}
for k, vs in editd.items():
    for kk, v in vs.items():
        cert[kk].extend(v)
acc1t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc1.items():
    for kk, v in vs.items():
        acc1t[kk].extend(v)

acc20t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc20.items():
    for kk, v in vs.items():
        acc20t[kk].extend(v)
print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

Some weights of BertForMaskedLM were not initialized from the model checkpoint at pranaydeeps/Ancient-Greek-BERT and are newly initialized: ['cls.predictions.bias', 'cls.predictions.decoder.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
100%|██████████| 95/95 [00:33<00:00,  2.87it/s]

======== atticionic ========
CER  : 93.19%
ACC1 : 0.00%
ACC20: 0.00%
======== doric ========
CER  : 96.10%
ACC1 : 0.00%
ACC20: 0.00%
======== northwest ========
CER  : 95.83%
ACC1 : 0.00%
ACC20: 0.00%
======== aeolic ========
CER  : 79.17%
ACC1 : 0.00%
ACC20: 0.00%
======== TOTAL ========
CER : 91.45%
ACC1 : 0.00%
ACC20 : 0.00%

## Fine-Tuning

AG BERT fine-tuning on the whole iPHI dataset.

In [6]:
from transformers import EarlyStoppingCallback

# Load pre-trained BERT model and tokenizer
#model_name = "bert-base-uncased"
model_name = "pranaydeeps/Ancient-Greek-BERT"
tokenizer = BertTokenizer.from_pretrained(model_name)
config = BertConfig.from_pretrained(model_name)
model = BertForMaskedLM.from_pretrained(model_name, config=config)

early_stopping = EarlyStoppingCallback(early_stopping_patience=3, early_stopping_threshold=0.0)

train_dataset = LineByLineTextDataset(
    tokenizer=tokenizer,
    file_path="data/iphi/train.txt",
    block_size=128,
)

data_collator = DataCollatorForLanguageModeling(
    #tokenizer=tokenizer, mlm=True, mlm_probability=0.15
    tokenizer=tokenizer, mlm=True, mlm_probability=0.15
)

training_args = TrainingArguments(
    output_dir="models/epi-agBERT",
    overwrite_output_dir=True,
    num_train_epochs=100,
    per_device_train_batch_size=32,
    save_steps=500,
    logging_steps=500,
    eval_steps=500,
    save_total_limit=2,
    evaluation_strategy = 'steps',
    metric_for_best_model= 'eval_loss',
    load_best_model_at_end = True,
    greater_is_better=False,
    logging_dir='./logs',
    report_to=["tensorboard"]
)

val_dataset = LineByLineTextDataset(
    tokenizer=tokenizer,
    file_path="data/iphi/validation.txt",
    block_size=128,
)

test_dataset = LineByLineTextDataset(
    tokenizer=tokenizer,
    file_path="data/iphi/test.txt",
    block_size=128,
)

trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    callbacks=[early_stopping]
)

test_result = trainer.evaluate(test_dataset)
print("Evaluation result:", test_result)
"""
Evaluation result: {'eval_loss': 11.396125793457031, 'eval_runtime': 22.5231, 'eval_samples_per_second': 346.8, 'eval_steps_per_second': 14.474}
"""

trainer.train()
trainer.save_model('models/epi-agBERT')
tokenizer.save_pretrained('models/epi-agBERT')

test_result = trainer.evaluate(test_dataset)
print("Evaluation result:", test_result)

# with open('log.txt', 'w') as f:
#     f.write(cap.stdout)

Some weights of BertForMaskedLM were not initialized from the model checkpoint at pranaydeeps/Ancient-Greek-BERT and are newly initialized: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/data01/alocaputo/miniconda3/envs/ancientGPT/lib/python3.9/site-packages/transformers/data/datasets/language_modeling.py:119: FutureWarning: This dataset will be removed from the library soon, preprocessing should be handled with the 🤗 Datasets library. You can have a look at this example script for pointers: https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_mlm.py
  warnings.warn(
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

Evaluation result: {'eval_loss': 10.620267868041992, 'eval_runtime': 22.2925, 'eval_samples_per_second': 350.297, 'eval_steps_per_second': 43.826}

KeyboardInterrupt:

Archaic

In [11]:
from transformers import EarlyStoppingCallback
import os

# Load pre-trained BERT model and tokenizer
#model_name = "bert-base-uncased"
model_name = "pranaydeeps/Ancient-Greek-BERT"
tokenizer = BertTokenizer.from_pretrained(model_name)
config = BertConfig.from_pretrained(model_name)
model = BertForMaskedLM.from_pretrained(model_name, config=config)

early_stopping = EarlyStoppingCallback(early_stopping_patience=3, early_stopping_threshold=0.0)

train_dataset = LineByLineTextDataset(
    tokenizer=tokenizer,
    file_path="data/archaic/train.txt",
    block_size=128,
)

data_collator = DataCollatorForLanguageModeling(
    #tokenizer=tokenizer, mlm=True, mlm_probability=0.15
    tokenizer=tokenizer, mlm=True, mlm_probability=0.15
)

training_args = TrainingArguments(
    output_dir="models/agBERT-archaic",
    overwrite_output_dir=True,
    num_train_epochs=10000,
    per_device_train_batch_size=32,
    save_steps=500,
    logging_steps=500,
    eval_steps=500,
    save_total_limit=2,
    evaluation_strategy = 'steps',
    metric_for_best_model= 'eval_loss',
    load_best_model_at_end = True,
    greater_is_better=False,
    logging_dir='./logs/archaic',
    run_name="agBERT-archaic",
)

val_dataset = LineByLineTextDataset(
    tokenizer=tokenizer,
    file_path="data/archaic/validation.txt",
    block_size=128,
)

test_dataset = LineByLineTextDataset(
    tokenizer=tokenizer,
    file_path="data/archaic/test.txt",
    block_size=128,
)

trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    callbacks=[early_stopping]
)

test_result = trainer.evaluate(test_dataset)
print("Evaluation result:", test_result)
"""
Evaluation result: {'eval_loss': 11.396125793457031, 'eval_runtime': 22.5231, 'eval_samples_per_second': 346.8, 'eval_steps_per_second': 14.474}
"""

trainer.train()
trainer.save_model('models/agBERT-archaic')
tokenizer.save_pretrained('models/agBERT-archaic')

test_result = trainer.evaluate(test_dataset)
print("Evaluation result:", test_result)

# with open('log.txt', 'w') as f:
#     f.write(cap.stdout)

Some weights of BertForMaskedLM were not initialized from the model checkpoint at pranaydeeps/Ancient-Greek-BERT and are newly initialized: ['cls.predictions.bias', 'cls.predictions.decoder.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/data01/alocaputo/miniconda3/envs/ancientGPT/lib/python3.9/site-packages/transformers/data/datasets/language_modeling.py:119: FutureWarning: This dataset will be removed from the library soon, preprocessing should be handled with the 🤗 Datasets library. You can have a look at this example script for pointers: https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_mlm.py
  warnings.warn(
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

Evaluation result: {'eval_loss': 10.873405456542969, 'eval_runtime': 0.3262, 'eval_samples_per_second': 291.234, 'eval_steps_per_second': 18.394}

/data01/alocaputo/miniconda3/envs/ancientGPT/lib/python3.9/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
/data01/alocaputo/miniconda3/envs/ancientGPT/lib/python3.9/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
/data01/alocaputo/miniconda3/envs/ancientGPT/lib/python3.9/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
/data01/alocaputo/miniconda3/envs/ancientGPT/lib/python3.9/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
/data01/alocaputo/miniconda3/envs/ancientGPT/lib/python3.9/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
There were missing keys in the checkpoint model loaded: ['cls.predictions.decoder.weight', 'cls.predictions.decoder.bias'].
/data01/alocaputo/miniconda3/envs/ancientGPT/lib/python3.9/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '

Evaluation result: {'eval_loss': 2.165879249572754, 'eval_runtime': 0.3262, 'eval_samples_per_second': 291.2, 'eval_steps_per_second': 18.392, 'epoch': 250.0}

## Fine-Tuned Eval

Without knowing the length of the gap.

In [ ]:
model_name = "./models/epi-agBERT"
fill_mask = pipeline("fill-mask", model=model_name, tokenizer=model_name, top_k=20)


editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc1 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}

for inscription in tqdm(test_set):
    ground_truth = inscription['masked_gt']
    masked = inscription['masked_ag']

    dialect = inscription['dialect']
    
    inference_result = fill_mask(masked)

    ctop1 = 0
    ctop20 = 0
    if ground_truth in [ x['token_str'] for x in inference_result[:1] ]:
        ctop1 = 1
        ctop20 = 1
    if ground_truth in [ x['token_str'] for x in inference_result ]:
        ctop20 = 1

    acc1[dialect][len(ground_truth)].append(ctop1)
    acc20[dialect][len(ground_truth)].append(ctop20)

    editd[dialect][len(ground_truth)].append(editdistance.eval(inference_result[0]['token_str'], ground_truth) / len(ground_truth))

for dialect in dialects:
    print(f"======== {dialect} ========")
    print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
    print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')

print(f"======== TOTAL ========")
cert = { x: [] for x in range(1, max_l+1)}
for k, vs in editd.items():
    for kk, v in vs.items():
        cert[kk].extend(v)
acc1t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc1.items():
    for kk, v in vs.items():
        acc1t[kk].extend(v)
acc20t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc20.items():
    for kk, v in vs.items():
        acc20t[kk].extend(v)
print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

100%|██████████| 95/95 [00:05<00:00, 16.09it/s]

======== atticionic ========
CER  : 88.27%
ACC1 : 12.25%
ACC20: 28.28%
======== doric ========
CER  : 80.49%
ACC1 : 10.00%
ACC20: 27.50%
======== northwest ========
CER  : 90.83%
ACC1 : 20.00%
ACC20: 30.00%
======== aeolic ========
CER  : 80.83%
ACC1 : 0.00%
ACC20: 0.00%
======== TOTAL ========
CER : 87.73%
ACC1 : 9.95%
ACC20 : 23.32%

Knowing the length of the gap.

In [16]:
model_name = "./models/epi-agBERT"
fill_mask = pipeline("fill-mask", model=model_name, tokenizer=model_name, top_k=3500)

ctop1s = []
ctop20s = []

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}

acc1 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}

pbar = tqdm(test_set)
for inscription in pbar:
    ground_truth = inscription['masked_gt']
    masked = inscription['masked_ag']

    dialect = inscription['dialect']
    
    inference_result = fill_mask(masked)

    constr = [ x for x in inference_result if len(x['token_str']) == len(ground_truth)][:20]

    ctop1 = 0
    ctop20 = 0
    if ground_truth in [ x['token_str'] for x in constr[:1] ]:
        ctop1 = 1
        ctop20 = 1
    if ground_truth in [ x['token_str'] for x in constr ]:
        ctop20 = 1

    ctop1s.append(ctop1)
    ctop20s.append(ctop20)
    acc1[dialect][len(ground_truth)].append(ctop1)
    acc20[dialect][len(ground_truth)].append(ctop20)

    if constr != []:
        editd[dialect][len(ground_truth)].append(editdistance.eval(constr[0]['token_str'], ground_truth) / len(ground_truth))
    else:
        editd[dialect][len(ground_truth)].append(1.0)

for dialect in dialects:
    print(f"======== {dialect} ========")
    print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
    print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')

print(f"======== TOTAL ========")
cert = { x: [] for x in range(1, max_l+1)}
for k, vs in editd.items():
    for kk, v in vs.items():
        cert[kk].extend(v)
acc1t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc1.items():
    for kk, v in vs.items():
        acc1t[kk].extend(v)

acc20t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc20.items():
    for kk, v in vs.items():
        acc20t[kk].extend(v)
print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

100%|██████████| 95/95 [00:33<00:00,  2.84it/s]

======== atticionic ========
CER  : 68.71%
ACC1 : 21.23%
ACC20: 28.28%
======== doric ========
CER  : 73.82%
ACC1 : 10.00%
ACC20: 27.50%
======== northwest ========
CER  : 65.00%
ACC1 : 30.00%
ACC20: 50.00%
======== aeolic ========
CER  : 89.17%
ACC1 : 0.00%
ACC20: 0.00%
======== TOTAL ========
CER : 73.11%
ACC1 : 15.82%
ACC20 : 25.19%

Archaic knowing the size (beam search).

In [9]:
from transformers import pipeline, AutoTokenizer
from tqdm import tqdm
import math

model_name = "./models/agBERT-archaic/" 
tokenizer = AutoTokenizer.from_pretrained(model_name)

fill_mask = pipeline("fill-mask", model=model_name, tokenizer=tokenizer, top_k=1000)

def beam_search(inference_result, target_length, final_k=20):
    search_width = 1500
    beam = [(0.0, [])] 
    
    for mask_pos_candidates in inference_result:
        new_beam = []
        for current_score, current_tokens in beam:
            for candidate in mask_pos_candidates:
                token_str = candidate['token_str']
                if "-" in token_str:
                    continue
                score = candidate['score']
                
                new_score = current_score + math.log(score if score > 0 else 1e-10)
                new_tokens = current_tokens + [token_str]
                new_beam.append((new_score, new_tokens))

        new_beam.sort(key=lambda x: x[0], reverse=True)
        beam = new_beam[:search_width]
    
    valid_candidates = []
    for _, tokens in beam:
        word = "".join(tokens).replace("##", "")
        if len(word) == target_length:
            valid_candidates.append(word)
            
    return valid_candidates[:final_k]


dialects = ['atticionic', 'doric', 'northwest', 'aeolic']
max_l = max(len(i['masked_gt']) for i in test_set) 

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc1 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
c1 = 0
c2 = 0
res = []
for inscription in tqdm(test_set):
    ground_truth = inscription['masked_gt']
    masked = inscription['masked_ag']
    dialect = inscription['dialect']
    gt_len = len(ground_truth)

    gt_tokens = tokenizer.tokenize(ground_truth)
    num_tokens = len(gt_tokens)

    multi_mask_str = " ".join(["[MASK]"] * num_tokens)
    masked_query = masked.replace("[MASK]", multi_mask_str)

    inference_result = fill_mask(masked_query)

    top_20_words = []
    
    if num_tokens == 1: # If the word is made of just one token (simple case)
        clean_candidates = [
            x['token_str'] for x in inference_result 
            if not x['token_str'].startswith("##") 
            and "-" not in x['token_str']
            and len(x['token_str']) == gt_len
        ]
        top_20_words = clean_candidates[:20]
        if len(top_20_words) != 20:
            c1 += 1
    else: # If the word is made of multiple tokens (beam search)
        top_20_words = beam_search(inference_result, gt_len, final_k=20)
    
        if len(top_20_words) != 20:
            c2 += 1

    found_in_top1 = False
    found_in_top20 = False
    
    if top_20_words:
        if top_20_words[0] == ground_truth:
            found_in_top1 = True
        if ground_truth in top_20_words:
            found_in_top20 = True

    if dialect in acc1 and gt_len in acc1[dialect]:
        acc1[dialect][gt_len].append(1 if found_in_top1 else 0)
        acc20[dialect][gt_len].append(1 if found_in_top20 else 0)
    
    editd[dialect][gt_len].append(editdistance.eval(top_20_words[0], ground_truth) / gt_len)
    res.append((masked, ground_truth, top_20_words))

for dialect in dialects:
    print(f"======== {dialect} ========")
    print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
    print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')
    
print(f"======== TOTAL ========")
acc1t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc1.items():
    for kk, v in vs.items():
        acc1t[kk].extend(v)

acc20t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc20.items():
    for kk, v in vs.items():
        acc20t[kk].extend(v)

cert = { x: [] for x in range(1, max_l+1)}
for k, vs in editd.items():
    for kk, v in vs.items():
        cert[kk].extend(v)
        
print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

print(c1, c2, c1+c2)

Device set to use cuda:0
100%|██████████| 95/95 [04:55<00:00,  3.11s/it]

======== atticionic ========
CER  : 48.09%
ACC1 : 33.93%
ACC20: 44.22%
======== doric ========
CER  : 45.85%
ACC1 : 37.50%
ACC20: 52.50%
======== northwest ========
CER  : 51.67%
ACC1 : 40.00%
ACC20: 50.00%
======== aeolic ========
CER  : 60.00%
ACC1 : 33.33%
ACC20: 33.33%
======== TOTAL ========
CER : 52.75%
ACC1 : 29.90%
ACC20 : 41.66%
1 2 3

AGBERT (beamsearch)

In [ ]:
model_name = "pranaydeeps/Ancient-Greek-BERT"
fill_mask = pipeline("fill-mask", model=model_name, tokenizer=model_name, top_k=3500)

ctop1s = []
ctop20s = []

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc1 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
for sentence in tqdm(test_set):

    masked = sentence['masked_ag']
    ground_truth = sentence['masked_gt']

    dialect = sentence['dialect']

    inference_result = fill_mask(masked)

    constr = [ x for x in inference_result if len(x['token_str']) == len(ground_truth)][:20]

    ctop1 = 0
    ctop20 = 0
    if ground_truth in [ x['token_str'] for x in constr[:1] ]:
        ctop20 = 1
        ctop1 = 1
    if ground_truth in [ x['token_str'] for x in constr ]:
        ctop20 = 1

    ctop1s.append(ctop1)
    ctop20s.append(ctop20)
    acc1[dialect][len(ground_truth)].append(ctop1)
    acc20[dialect][len(ground_truth)].append(ctop20)

    if constr != []:
        editd[dialect][len(ground_truth)].append(editdistance.eval(constr[0]['token_str'], ground_truth) / len(ground_truth))
    else:
        editd[dialect][len(ground_truth)].append(1.0)

for dialect in dialects:
    print(f"======== {dialect} ========")
    print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
    print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')

print(f"======== TOTAL ========")
cert = { x: [] for x in range(1, max_l+1)}
for k, vs in editd.items():
    for kk, v in vs.items():
        cert[kk].extend(v)
acc1t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc1.items():
    for kk, v in vs.items():
        acc1t[kk].extend(v)

acc20t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc20.items():
    for kk, v in vs.items():
        acc20t[kk].extend(v)
print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

Some weights of BertForMaskedLM were not initialized from the model checkpoint at pranaydeeps/Ancient-Greek-BERT and are newly initialized: ['cls.predictions.bias', 'cls.predictions.decoder.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Device set to use cuda:0
100%|██████████| 95/95 [00:30<00:00,  3.09it/s]

======== atticionic ========
CER  : 91.00%
ACC1 : 0.00%
ACC20: 1.28%
======== doric ========
CER  : 97.01%
ACC1 : 0.00%
ACC20: 0.00%
======== northwest ========
CER  : 96.67%
ACC1 : 0.00%
ACC20: 10.00%
======== aeolic ========
CER  : 87.50%
ACC1 : 0.00%
ACC20: 0.00%
======== TOTAL ========
CER : 92.53%
ACC1 : 0.00%
ACC20 : 1.74%

In [12]:
from transformers import pipeline, AutoTokenizer
from tqdm import tqdm
import math

model_name = "pranaydeeps/Ancient-Greek-BERT"
tokenizer = AutoTokenizer.from_pretrained(model_name)

fill_mask = pipeline("fill-mask", model=model_name, tokenizer=tokenizer, top_k=1000)

def beam_search(inference_result, target_length, final_k=20):
    search_width = 1500
    beam = [(0.0, [])] 
    
    for mask_pos_candidates in inference_result:
        new_beam = []
        for current_score, current_tokens in beam:
            for candidate in mask_pos_candidates:
                token_str = candidate['token_str']
                if "-" in token_str:
                    continue
                score = candidate['score']
                
                new_score = current_score + math.log(score if score > 0 else 1e-10)
                new_tokens = current_tokens + [token_str]
                new_beam.append((new_score, new_tokens))

        new_beam.sort(key=lambda x: x[0], reverse=True)
        beam = new_beam[:search_width]
    
    valid_candidates = []
    for _, tokens in beam:
        word = "".join(tokens).replace("##", "")
        if len(word) == target_length:
            valid_candidates.append(word)
            
    return valid_candidates[:final_k]


dialects = ['atticionic', 'doric', 'northwest', 'aeolic']
max_l = max(len(i['masked_gt']) for i in test_set) 

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc1 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
c1 = 0
c2 = 0
res = []
for inscription in tqdm(test_set):
    ground_truth = inscription['masked_gt']
    masked = inscription['masked_ag']
    dialect = inscription['dialect']
    gt_len = len(ground_truth)

    gt_tokens = tokenizer.tokenize(ground_truth)
    num_tokens = len(gt_tokens)

    multi_mask_str = " ".join(["[MASK]"] * num_tokens)
    masked_query = masked.replace("[MASK]", multi_mask_str)

    inference_result = fill_mask(masked_query)

    top_20_words = []
    
    if num_tokens == 1: # If the word is made of just one token (simple case)
        clean_candidates = [
            x['token_str'] for x in inference_result 
            if not x['token_str'].startswith("##") 
            and "-" not in x['token_str']
            and len(x['token_str']) == gt_len
        ]
        top_20_words = clean_candidates[:20]
        if len(top_20_words) != 20:
            c1 += 1
    else: # If the word is made of multiple tokens (beam search)
        top_20_words = beam_search(inference_result, gt_len, final_k=20)
    
        if len(top_20_words) != 20:
            c2 += 1

    found_in_top1 = False
    found_in_top20 = False
    
    if top_20_words:
        if top_20_words[0] == ground_truth:
            found_in_top1 = True
        if ground_truth in top_20_words:
            found_in_top20 = True

    if dialect in acc1 and gt_len in acc1[dialect]:
        acc1[dialect][gt_len].append(1 if found_in_top1 else 0)
        acc20[dialect][gt_len].append(1 if found_in_top20 else 0)
    
    if len(top_20_words) > 0:
        editd[dialect][gt_len].append(editdistance.eval(top_20_words[0], ground_truth) / gt_len)
    else:
        editd[dialect][gt_len].append(1.0)
    res.append((masked, ground_truth, top_20_words))

for dialect in dialects:
    print(f"======== {dialect} ========")
    print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
    print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')
    
print(f"======== TOTAL ========")
acc1t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc1.items():
    for kk, v in vs.items():
        acc1t[kk].extend(v)

acc20t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc20.items():
    for kk, v in vs.items():
        acc20t[kk].extend(v)

cert = { x: [] for x in range(1, max_l+1)}
for k, vs in editd.items():
    for kk, v in vs.items():
        cert[kk].extend(v)
        
print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

print(c1, c2, c1+c2)

Some weights of BertForMaskedLM were not initialized from the model checkpoint at pranaydeeps/Ancient-Greek-BERT and are newly initialized: ['cls.predictions.bias', 'cls.predictions.decoder.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Device set to use cuda:0
100%|██████████| 95/95 [05:00<00:00,  3.16s/it]

======== atticionic ========
CER  : 91.13%
ACC1 : 0.00%
ACC20: 1.92%
======== doric ========
CER  : 95.84%
ACC1 : 0.00%
ACC20: 0.00%
======== northwest ========
CER  : 99.17%
ACC1 : 0.00%
ACC20: 30.00%
======== aeolic ========
CER  : 100.00%
ACC1 : 0.00%
ACC20: 0.00%
======== TOTAL ========
CER : 93.04%
ACC1 : 0.00%
ACC20 : 3.48%
9 41 50

In [3]:
model_name = "./models/epi-agBERT"
fill_mask = pipeline("fill-mask", model=model_name, tokenizer=model_name, top_k=3500)

ctop1s = []
ctop20s = []

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}

acc1 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}

pbar = tqdm(test_set)
for inscription in pbar:
    ground_truth = inscription['masked_gt']
    masked = inscription['masked_ag']

    dialect = inscription['dialect']
    
    inference_result = fill_mask(masked)

    constr = [ x for x in inference_result if len(x['token_str']) == len(ground_truth)][:20]

    ctop1 = 0
    ctop20 = 0
    if ground_truth in [ x['token_str'] for x in constr[:1] ]:
        ctop1 = 1
        ctop20 = 1
    if ground_truth in [ x['token_str'] for x in constr ]:
        ctop20 = 1

    ctop1s.append(ctop1)
    ctop20s.append(ctop20)
    acc1[dialect][len(ground_truth)].append(ctop1)
    acc20[dialect][len(ground_truth)].append(ctop20)

    if constr != []:
        editd[dialect][len(ground_truth)].append(editdistance.eval(constr[0]['token_str'], ground_truth) / len(ground_truth))
    else:
        editd[dialect][len(ground_truth)].append(1.0)

for dialect in dialects:
    print(f"======== {dialect} ========")
    print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
    print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')

print(f"======== TOTAL ========")
cert = { x: [] for x in range(1, max_l+1)}
for k, vs in editd.items():
    for kk, v in vs.items():
        cert[kk].extend(v)
acc1t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc1.items():
    for kk, v in vs.items():
        acc1t[kk].extend(v)

acc20t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc20.items():
    for kk, v in vs.items():
        acc20t[kk].extend(v)
print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

BertForMaskedLM has generative capabilities, as `prepare_inputs_for_generation` is explicitly overwritten. However, it doesn't directly inherit from `GenerationMixin`. From 👉v4.50👈 onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
  - If you're using `trust_remote_code=True`, you can get rid of this warning by loading the model with an auto class. See https://huggingface.co/docs/transformers/en/model_doc/auto#auto-classes
  - If you are the owner of the model architecture code, please modify your model class such that it inherits from `GenerationMixin` (after `PreTrainedModel`, otherwise you'll get an exception).
  - If you are not the owner of the model architecture class, please contact the model code owner to update it.
Device set to use cuda:0
 11%|█         | 10/95 [00:03<00:22,  3.75it/s]You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
100%|██████████| 95/95 [00:32<00:00,  2.89it/s]

======== atticionic ========
CER  : 64.90%
ACC1 : 23.15%
ACC20: 28.28%
======== doric ========
CER  : 67.30%
ACC1 : 20.00%
ACC20: 27.50%
======== northwest ========
CER  : 70.00%
ACC1 : 20.00%
ACC20: 50.00%
======== aeolic ========
CER  : 95.83%
ACC1 : 0.00%
ACC20: 0.00%
======== TOTAL ========
CER : 71.64%
ACC1 : 17.28%
ACC20 : 25.06%

In [7]:
from transformers import pipeline, AutoTokenizer
from tqdm import tqdm
import math

model_name = "./models/epi-agBERT"
tokenizer = AutoTokenizer.from_pretrained(model_name)

fill_mask = pipeline("fill-mask", model=model_name, tokenizer=tokenizer, top_k=1000)

def beam_search(inference_result, target_length, final_k=20):
    search_width = 1500
    beam = [(0.0, [])] 
    
    for mask_pos_candidates in inference_result:
        new_beam = []
        for current_score, current_tokens in beam:
            for candidate in mask_pos_candidates:
                token_str = candidate['token_str']
                if "-" in token_str:
                    continue
                score = candidate['score']
                
                new_score = current_score + math.log(score if score > 0 else 1e-10)
                new_tokens = current_tokens + [token_str]
                new_beam.append((new_score, new_tokens))

        new_beam.sort(key=lambda x: x[0], reverse=True)
        beam = new_beam[:search_width]
    
    valid_candidates = []
    for _, tokens in beam:
        word = "".join(tokens).replace("##", "")
        if len(word) == target_length:
            valid_candidates.append(word)
            
    return valid_candidates[:final_k]


dialects = ['atticionic', 'doric', 'northwest', 'aeolic']
max_l = max(len(i['masked_gt']) for i in test_set) 

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc1 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
c1 = 0
c2 = 0
res = []
for inscription in tqdm(test_set):
    ground_truth = inscription['masked_gt']
    masked = inscription['masked_ag']
    dialect = inscription['dialect']
    gt_len = len(ground_truth)

    gt_tokens = tokenizer.tokenize(ground_truth)
    num_tokens = len(gt_tokens)

    multi_mask_str = " ".join(["[MASK]"] * num_tokens)
    masked_query = masked.replace("[MASK]", multi_mask_str)

    inference_result = fill_mask(masked_query)

    top_20_words = []
    
    if num_tokens == 1: # If the word is made of just one token (simple case)
        clean_candidates = [
            x['token_str'] for x in inference_result 
            if not x['token_str'].startswith("##") 
            and "-" not in x['token_str']
            and len(x['token_str']) == gt_len
        ]
        top_20_words = clean_candidates[:20]
        if len(top_20_words) != 20:
            c1 += 1
    else: # If the word is made of multiple tokens (beam search)
        top_20_words = beam_search(inference_result, gt_len, final_k=20)
    
        if len(top_20_words) != 20:
            c2 += 1

    found_in_top1 = False
    found_in_top20 = False
    
    if top_20_words:
        if top_20_words[0] == ground_truth:
            found_in_top1 = True
        if ground_truth in top_20_words:
            found_in_top20 = True

    if dialect in acc1 and gt_len in acc1[dialect]:
        acc1[dialect][gt_len].append(1 if found_in_top1 else 0)
        acc20[dialect][gt_len].append(1 if found_in_top20 else 0)
    
    if len(top_20_words) > 0:
        editd[dialect][gt_len].append(editdistance.eval(top_20_words[0], ground_truth) / gt_len)
    else:
        editd[dialect][gt_len].append(1.0)
    res.append((masked, ground_truth, top_20_words))

for dialect in dialects:
    print(f"======== {dialect} ========")
    print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
    print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')
    
print(f"======== TOTAL ========")
acc1t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc1.items():
    for kk, v in vs.items():
        acc1t[kk].extend(v)

acc20t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc20.items():
    for kk, v in vs.items():
        acc20t[kk].extend(v)

cert = { x: [] for x in range(1, max_l+1)}
for k, vs in editd.items():
    for kk, v in vs.items():
        cert[kk].extend(v)
        
print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

print(c1, c2, c1+c2)

Device set to use cuda:0
100%|██████████| 95/95 [04:51<00:00,  3.06s/it]

======== atticionic ========
CER  : 62.11%
ACC1 : 28.21%
ACC20: 34.89%
======== doric ========
CER  : 56.70%
ACC1 : 32.50%
ACC20: 45.00%
======== northwest ========
CER  : 71.67%
ACC1 : 20.00%
ACC20: 60.00%
======== aeolic ========
CER  : 66.67%
ACC1 : 33.33%
ACC20: 33.33%
======== TOTAL ========
CER : 67.17%
ACC1 : 23.20%
ACC20 : 33.38%
1 10 11

## Other models

### Logion 
"princeton-logion/logion-bert-base"

In [ ]:
import re

greek_pattern = re.compile(r"^[\u0370-\u03FF\u1F00-\u1FFF]+$")

model_name = "princeton-logion/logion-bert-base"
fill_mask = pipeline("fill-mask", model=model_name, tokenizer=model_name, top_k=3500)

ctop1s = []
ctop20s = []

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}

acc1 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}

pbar = tqdm(test_set)
res = []
for inscription in pbar:
    ground_truth = inscription['masked_gt']
    masked = inscription['masked_ag']

    dialect = inscription['dialect']
    
    inference_result = fill_mask(masked)

    constr = list(dict.fromkeys([
    strip_accents(x['token_str']) 
    for x in inference_result 
    if len(x['token_str']) == len(ground_truth)
    and not x['token_str'].startswith("<extra_id_")
    and greek_pattern.match(strip_accents(x['token_str']))
    ]))[:20]
    
    res.append((masked, ground_truth, constr))

    ctop1 = 0
    ctop20 = 0
    if ground_truth in [ x for x in constr[:1] ]:
        ctop1 = 1
        ctop20 = 1
    if ground_truth in [ x for x in constr ]:
        ctop20 = 1

    ctop1s.append(ctop1)
    ctop20s.append(ctop20)
    acc1[dialect][len(ground_truth)].append(ctop1)
    acc20[dialect][len(ground_truth)].append(ctop20)

    if constr != []:
        editd[dialect][len(ground_truth)].append(editdistance.eval(strip_accents(constr[0]), ground_truth) / len(ground_truth))
    else:
        editd[dialect][len(ground_truth)].append(1.0)

for dialect in dialects:
    print(f"======== {dialect} ========")
    print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
    print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')

print(f"======== TOTAL ========")
cert = { x: [] for x in range(1, max_l+1)}
for k, vs in editd.items():
    for kk, v in vs.items():
        cert[kk].extend(v)
acc1t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc1.items():
    for kk, v in vs.items():
        acc1t[kk].extend(v)

acc20t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc20.items():
    for kk, v in vs.items():
        acc20t[kk].extend(v)
print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

Device set to use cuda:0
100%|██████████| 95/95 [00:25<00:00,  3.66it/s]

======== atticionic ========
CER  : 69.09%
ACC1 : 9.23%
ACC20: 29.82%
======== doric ========
CER  : 86.22%
ACC1 : 0.00%
ACC20: 32.50%
======== northwest ========
CER  : 77.50%
ACC1 : 0.00%
ACC20: 70.00%
======== aeolic ========
CER  : 93.33%
ACC1 : 0.00%
ACC20: 0.00%
======== TOTAL ========
CER : 75.69%
ACC1 : 5.27%
ACC20 : 28.40%

In [27]:
from transformers import pipeline, AutoTokenizer
from tqdm import tqdm
import math

model_name = "princeton-logion/logion-bert-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)

fill_mask = pipeline("fill-mask", model=model_name, tokenizer=tokenizer, top_k=3500)

def beam_search(inference_result, target_length, final_k=20):
    search_width = 30
    beam = [(0.0, [])] 
    
    for mask_pos_candidates in inference_result:
        new_beam = []
        for current_score, current_tokens in beam:
            for candidate in mask_pos_candidates:
                token_str = candidate['token_str']
                if "-" in token_str:
                    continue
                score = candidate['score']
                
                new_score = current_score + math.log(score if score > 0 else 1e-10)
                new_tokens = current_tokens + [token_str]
                new_beam.append((new_score, new_tokens))

        new_beam.sort(key=lambda x: x[0], reverse=True)
        beam = new_beam[:search_width]
    
    valid_candidates = []
    for _, tokens in beam:
        word = "".join(tokens).replace("##", "")
        if len(word) == target_length:
            valid_candidates.append(word)
            
    return [x for x in valid_candidates if greek_pattern.match(x)][:final_k]


dialects = ['atticionic', 'doric', 'northwest', 'aeolic']
max_l = max(len(i['masked_gt']) for i in test_set) 

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc1 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
c1 = 0
c2 = 0
res = []
for inscription in tqdm(test_set):
    ground_truth = inscription['masked_gt']
    masked = inscription['masked_ag']
    dialect = inscription['dialect']
    gt_len = len(ground_truth)

    gt_tokens = tokenizer.tokenize(ground_truth)
    num_tokens = len(gt_tokens)

    multi_mask_str = " ".join(["[MASK]"] * num_tokens)
    masked_query = masked.replace("[MASK]", multi_mask_str)

    inference_result = fill_mask(masked_query)

    top_20_words = []
    
    if num_tokens == 1: # If the word is made of just one token (simple case)

        clean_candidates = list(dict.fromkeys([
            x['token_str'] 
            for x in inference_result 
            if len(x['token_str']) == len(ground_truth)
            and not x['token_str'].startswith("<extra_id_")
            and greek_pattern.match(x['token_str'])
        ]))
        
        top_20_words = clean_candidates[:20]
        res.append((0, masked, ground_truth, top_20_words))
        if len(top_20_words) != 20:
            c1 += 1
    else: # If the word is made of multiple tokens (beam search)
        top_20_words = beam_search(inference_result, gt_len, final_k=20)
        res.append((1, masked, ground_truth, top_20_words))
    
        if len(top_20_words) != 20:
            c2 += 1

    found_in_top1 = False
    found_in_top20 = False
    
    if top_20_words:
        if top_20_words[0] == ground_truth:
            found_in_top1 = True
        if ground_truth in top_20_words:
            found_in_top20 = True

    if dialect in acc1 and gt_len in acc1[dialect]:
        acc1[dialect][gt_len].append(1 if found_in_top1 else 0)
        acc20[dialect][gt_len].append(1 if found_in_top20 else 0)
    
    if len(top_20_words) > 0:
        editd[dialect][gt_len].append(editdistance.eval(top_20_words[0], ground_truth) / gt_len)
    else:
        editd[dialect][gt_len].append(1.0)
    

for dialect in dialects:
    print(f"======== {dialect} ========")
    print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
    print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')
    
print(f"======== TOTAL ========")
acc1t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc1.items():
    for kk, v in vs.items():
        acc1t[kk].extend(v)

acc20t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc20.items():
    for kk, v in vs.items():
        acc20t[kk].extend(v)

cert = { x: [] for x in range(1, max_l+1)}
for k, vs in editd.items():
    for kk, v in vs.items():
        cert[kk].extend(v)
        
print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

print(c1, c2, c1+c2)

Device set to use cuda:0
100%|██████████| 95/95 [01:07<00:00,  1.40it/s]

======== atticionic ========
CER  : 80.57%
ACC1 : 9.23%
ACC20: 29.82%
======== doric ========
CER  : 90.35%
ACC1 : 2.50%
ACC20: 35.00%
======== northwest ========
CER  : 83.33%
ACC1 : 0.00%
ACC20: 70.00%
======== aeolic ========
CER  : 85.00%
ACC1 : 0.00%
ACC20: 0.00%
======== TOTAL ========
CER : 84.37%
ACC1 : 5.62%
ACC20 : 28.75%
2 53 55

### GreBERTa
"bowphs/GreBerta"

In [14]:
def inference_simple(model_name, roberta=False):
    fill_mask = pipeline("fill-mask", model=model_name, tokenizer=model_name, top_k=3500)

    ctop1s = []
    ctop20s = []

    editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}

    acc1 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
    acc20 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}

    pbar = tqdm(test_set)
    for inscription in pbar:
        ground_truth = inscription['masked_gt']
        masked = inscription['masked_ag']

        if roberta:
            masked = masked.replace("[MASK]", "<mask>")

        dialect = inscription['dialect']
        
        inference_result = fill_mask(masked)

        constr = [ x for x in inference_result if len(x['token_str']) == len(ground_truth)][:20]

        ctop1 = 0
        ctop20 = 0
        if ground_truth in [ x['token_str'] for x in constr[:1] ]:
            ctop1 = 1
            ctop20 = 1
        if ground_truth in [ x['token_str'] for x in constr ]:
            ctop20 = 1

        ctop1s.append(ctop1)
        ctop20s.append(ctop20)
        acc1[dialect][len(ground_truth)].append(ctop1)
        acc20[dialect][len(ground_truth)].append(ctop20)

        if constr != []:
            editd[dialect][len(ground_truth)].append(editdistance.eval(constr[0]['token_str'], ground_truth) / len(ground_truth))
        else:
            editd[dialect][len(ground_truth)].append(1.0)

    for dialect in dialects:
        print(f"======== {dialect} ========")
        print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
        print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
        print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')

    print(f"======== TOTAL ========")
    cert = { x: [] for x in range(1, max_l+1)}
    for k, vs in editd.items():
        for kk, v in vs.items():
            cert[kk].extend(v)
    acc1t = { x: [] for x in range(1, max_l+1)}
    for k, vs in acc1.items():
        for kk, v in vs.items():
            acc1t[kk].extend(v)

    acc20t = { x: [] for x in range(1, max_l+1)}
    for k, vs in acc20.items():
        for kk, v in vs.items():
            acc20t[kk].extend(v)
    print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
    print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

In [19]:
from transformers import pipeline, AutoTokenizer
from tqdm import tqdm
import math

def inference_beam(model_name, roberta=False):
    tokenizer = AutoTokenizer.from_pretrained(model_name)

    fill_mask = pipeline("fill-mask", model=model_name, tokenizer=tokenizer, top_k=1000)

    def beam_search(inference_result, target_length, final_k=20):
        if isinstance(inference_result[0], dict):
            inference_result = [inference_result]
        search_width = 1500
        beam = [(0.0, [])] 
        
        for mask_pos_candidates in inference_result:
            new_beam = []
            for current_score, current_tokens in beam:
                for candidate in mask_pos_candidates:
                    token_str = candidate['token_str']
                    if "-" in token_str:
                        continue
                    score = candidate['score']
                    
                    new_score = current_score + math.log(score if score > 0 else 1e-10)
                    new_tokens = current_tokens + [token_str]
                    new_beam.append((new_score, new_tokens))

            new_beam.sort(key=lambda x: x[0], reverse=True)
            beam = new_beam[:search_width]
        
        valid_candidates = []
        for _, tokens in beam:
            if roberta:
                word = "".join(tokens).strip().replace(" ", "")
            else:
                word = "".join(tokens).replace("##", "")
            if len(word) == target_length:
                valid_candidates.append(word)
                
        return valid_candidates[:final_k]


    dialects = ['atticionic', 'doric', 'northwest', 'aeolic']
    max_l = max(len(i['masked_gt']) for i in test_set) 

    editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
    acc1 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
    acc20 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
    c1 = 0
    c2 = 0
    res = []
    for inscription in tqdm(test_set):
        ground_truth = inscription['masked_gt']
        masked = inscription['masked_ag']
        dialect = inscription['dialect']
        gt_len = len(ground_truth)

        gt_tokens = tokenizer.tokenize(ground_truth)
        num_tokens = len(gt_tokens)

        multi_mask_str = " ".join(["[MASK]"] * num_tokens)
        masked_query = masked.replace("[MASK]", multi_mask_str)

        masked_query = masked.replace("[MASK]", "<mask>")
        inference_result = fill_mask(masked_query)

        top_20_words = []
        
        if num_tokens == 1: # If the word is made of just one token (simple case)
            clean_candidates = [
                x['token_str'] for x in inference_result 
                if not x['token_str'].startswith("##") 
                and "-" not in x['token_str']
                and len(x['token_str']) == gt_len
            ]
            top_20_words = clean_candidates[:20]
            if len(top_20_words) != 20:
                c1 += 1
        else: # If the word is made of multiple tokens (beam search)
            top_20_words = beam_search(inference_result, gt_len, final_k=20)
        
            if len(top_20_words) != 20:
                c2 += 1

        found_in_top1 = False
        found_in_top20 = False
        
        if top_20_words:
            if top_20_words[0] == ground_truth:
                found_in_top1 = True
            if ground_truth in top_20_words:
                found_in_top20 = True

        if dialect in acc1 and gt_len in acc1[dialect]:
            acc1[dialect][gt_len].append(1 if found_in_top1 else 0)
            acc20[dialect][gt_len].append(1 if found_in_top20 else 0)
        
        if len(top_20_words) > 0:
            editd[dialect][gt_len].append(editdistance.eval(top_20_words[0], ground_truth) / gt_len)
        else:
            editd[dialect][gt_len].append(1.0)
        res.append((masked, ground_truth, top_20_words))

    for dialect in dialects:
        print(f"======== {dialect} ========")
        print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
        print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
        print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')
        
    print(f"======== TOTAL ========")
    acc1t = { x: [] for x in range(1, max_l+1)}
    for k, vs in acc1.items():
        for kk, v in vs.items():
            acc1t[kk].extend(v)

    acc20t = { x: [] for x in range(1, max_l+1)}
    for k, vs in acc20.items():
        for kk, v in vs.items():
            acc20t[kk].extend(v)

    cert = { x: [] for x in range(1, max_l+1)}
    for k, vs in editd.items():
        for kk, v in vs.items():
            cert[kk].extend(v)
            
    print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
    print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

    print(c1, c2, c1+c2)

In [92]:
tokenizer = AutoTokenizer.from_pretrained("bowphs/GreBerta")
roberta = True
strict_greek_pattern = re.compile(r"^[α-ω]+$")
fill_mask = pipeline("fill-mask", model="bowphs/GreBerta", tokenizer=tokenizer, top_k=5000)

def beam_search(inference_result, target_length, final_k=20):
    if isinstance(inference_result[0], dict):
        inference_result = [inference_result]
    search_width = 1500
    beam = [(0.0, [])] 
    
    for mask_pos_candidates in inference_result:
        new_beam = []
        for current_score, current_tokens in beam:
            for candidate in mask_pos_candidates:
                token_str = candidate['token_str']
                if "-" in token_str:
                    continue
                score = candidate['score']
                
                new_score = current_score + math.log(score if score > 0 else 1e-10)
                new_tokens = current_tokens + [token_str]
                new_beam.append((new_score, new_tokens))

        new_beam.sort(key=lambda x: x[0], reverse=True)
        beam = new_beam[:search_width]
    
    valid_candidates = []
    for _, tokens in beam:
        if roberta:
            word = "".join(tokens).strip().replace(" ", "")
        else:
            word = "".join(tokens).replace("##", "")
        if len(word) == target_length:
            valid_candidates.append(word)

    valid_candidates = list(dict.fromkeys([
            strip_accents(x.lower())
            for x in valid_candidates 
            if len(x.replace(' ', '')) == target_length
            and strict_greek_pattern.match(strip_accents(x))
        ]))
    return valid_candidates[:final_k]


dialects = ['atticionic', 'doric', 'northwest', 'aeolic']
max_l = max(len(i['masked_gt']) for i in test_set) 

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc1 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
c1 = 0
c2 = 0
res = []
for inscription in tqdm(test_set):
    ground_truth = inscription['masked_gt']
    masked = inscription['masked_ag']
    dialect = inscription['dialect']
    gt_len = len(ground_truth)

    gt_tokens = tokenizer.tokenize(ground_truth)
    num_tokens = len(gt_tokens)

    multi_mask_str = " ".join(["[MASK]"] * num_tokens)
    masked_query = masked.replace("[MASK]", multi_mask_str)

    masked_query = masked.replace("[MASK]", "<mask>")
    inference_result = fill_mask(masked_query)

    top_20_words = []
    
    if num_tokens == 1: # If the word is made of just one token (simple case)
        # clean_candidates = [
        #     x['token_str'] for x in inference_result 
        #     if not x['token_str'].startswith("##") 
        #     and "-" not in x['token_str']
        #     and len(x['token_str']) == gt_len
        # ]
        clean_candidates = list(dict.fromkeys([
            strip_accents(x['token_str'].lower())
            for x in inference_result 
            if len(x['token_str'].replace(' ', '')) == len(ground_truth)
            and strict_greek_pattern.match(strip_accents(x['token_str']))
        ]))
        top_20_words = clean_candidates[:20]
        res.append((0, masked, ground_truth, top_20_words))
        if len(top_20_words) != 20:
            c1 += 1
    else: # If the word is made of multiple tokens (beam search)
        top_20_words = beam_search(inference_result, gt_len, final_k=20)
        res.append((1, masked, ground_truth, top_20_words))
    
        if len(top_20_words) != 20:
            c2 += 1

    found_in_top1 = False
    found_in_top20 = False
    
    if top_20_words:
        if top_20_words[0] == ground_truth:
            found_in_top1 = True
        if ground_truth in top_20_words:
            found_in_top20 = True

    if dialect in acc1 and gt_len in acc1[dialect]:
        acc1[dialect][gt_len].append(1 if found_in_top1 else 0)
        acc20[dialect][gt_len].append(1 if found_in_top20 else 0)
    
    if len(top_20_words) > 0:
        editd[dialect][gt_len].append(editdistance.eval(top_20_words[0], ground_truth) / gt_len)
    else:
        editd[dialect][gt_len].append(1.0)

for dialect in dialects:
    print(f"======== {dialect} ========")
    print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
    print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')
    
print(f"======== TOTAL ========")
acc1t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc1.items():
    for kk, v in vs.items():
        acc1t[kk].extend(v)

acc20t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc20.items():
    for kk, v in vs.items():
        acc20t[kk].extend(v)

cert = { x: [] for x in range(1, max_l+1)}
for k, vs in editd.items():
    for kk, v in vs.items():
        cert[kk].extend(v)
        
print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

print(c1, c2, c1+c2)

Device set to use cuda:0
100%|██████████| 95/95 [00:31<00:00,  3.01it/s]

======== atticionic ========
CER  : 87.72%
ACC1 : 0.00%
ACC20: 13.46%
======== doric ========
CER  : 91.14%
ACC1 : 0.00%
ACC20: 5.00%
======== northwest ========
CER  : 71.67%
ACC1 : 20.00%
ACC20: 50.00%
======== aeolic ========
CER  : 85.00%
ACC1 : 0.00%
ACC20: 0.00%
======== TOTAL ========
CER : 87.12%
ACC1 : 1.28%
ACC20 : 13.00%
7 5 12

In [21]:
model_name = "bowphs/GreBerta"
print("Simple")
inference_simple(model_name, roberta=True)
print("\n\nBeam")
inference_beam(model_name, roberta=True)

Simple

Device set to use cuda:0
100%|██████████| 95/95 [00:21<00:00,  4.42it/s]

======== atticionic ========
CER  : 96.24%
ACC1 : 0.00%
ACC20: 0.00%
======== doric ========
CER  : 93.98%
ACC1 : 0.00%
ACC20: 0.00%
======== northwest ========
CER  : 86.67%
ACC1 : 0.00%
ACC20: 20.00%
======== aeolic ========
CER  : 95.83%
ACC1 : 0.00%
ACC20: 0.00%
======== TOTAL ========
CER : 94.30%
ACC1 : 0.00%
ACC20 : 1.28%


Beam

Device set to use cuda:0
100%|██████████| 95/95 [00:07<00:00, 13.40it/s]

======== atticionic ========
CER  : 92.34%
ACC1 : 0.00%
ACC20: 0.00%
======== doric ========
CER  : 95.89%
ACC1 : 0.00%
ACC20: 0.00%
======== northwest ========
CER  : 86.67%
ACC1 : 0.00%
ACC20: 20.00%
======== aeolic ========
CER  : 85.00%
ACC1 : 0.00%
ACC20: 0.00%
======== TOTAL ========
CER : 92.66%
ACC1 : 0.00%
ACC20 : 1.28%
0 6 6

### PhilBERTa
"bowphs/PhilBerta"

In [22]:
model_name = "bowphs/PhilBerta"
print("Simple")
inference_simple(model_name, roberta=True)
print("\n\nBeam")
inference_beam(model_name, roberta=True)

Simple

Device set to use cuda:0
100%|██████████| 95/95 [00:20<00:00,  4.57it/s]

======== atticionic ========
CER  : 94.54%
ACC1 : 0.00%
ACC20: 10.90%
======== doric ========
CER  : 94.43%
ACC1 : 0.00%
ACC20: 0.00%
======== northwest ========
CER  : 95.00%
ACC1 : 0.00%
ACC20: 40.00%
======== aeolic ========
CER  : 93.33%
ACC1 : 0.00%
ACC20: 0.00%
======== TOTAL ========
CER : 93.83%
ACC1 : 0.00%
ACC20 : 9.80%


Beam

Device set to use cuda:0
100%|██████████| 95/95 [00:07<00:00, 13.30it/s]

======== atticionic ========
CER  : 93.42%
ACC1 : 0.00%
ACC20: 10.90%
======== doric ========
CER  : 93.97%
ACC1 : 0.00%
ACC20: 0.00%
======== northwest ========
CER  : 90.00%
ACC1 : 10.00%
ACC20: 40.00%
======== aeolic ========
CER  : 93.33%
ACC1 : 0.00%
ACC20: 0.00%
======== TOTAL ========
CER : 93.66%
ACC1 : 1.10%
ACC20 : 9.80%
0 27 27

In [94]:
tokenizer = AutoTokenizer.from_pretrained("bowphs/PhilBerta")
roberta = True
strict_greek_pattern = re.compile(r"^[α-ω]+$")
fill_mask = pipeline("fill-mask", model="bowphs/PhilBerta", tokenizer=tokenizer, top_k=5000)

def beam_search(inference_result, target_length, final_k=20):
    if isinstance(inference_result[0], dict):
        inference_result = [inference_result]
    search_width = 1500
    beam = [(0.0, [])] 
    
    for mask_pos_candidates in inference_result:
        new_beam = []
        for current_score, current_tokens in beam:
            for candidate in mask_pos_candidates:
                token_str = candidate['token_str']
                if "-" in token_str:
                    continue
                score = candidate['score']
                
                new_score = current_score + math.log(score if score > 0 else 1e-10)
                new_tokens = current_tokens + [token_str]
                new_beam.append((new_score, new_tokens))

        new_beam.sort(key=lambda x: x[0], reverse=True)
        beam = new_beam[:search_width]
    
    valid_candidates = []
    for _, tokens in beam:
        if roberta:
            word = "".join(tokens).strip().replace(" ", "")
        else:
            word = "".join(tokens).replace("##", "")
        if len(word) == target_length:
            valid_candidates.append(word)

    valid_candidates = list(dict.fromkeys([
            strip_accents(x.lower())
            for x in valid_candidates 
            if len(x.replace(' ', '')) == target_length
            and strict_greek_pattern.match(strip_accents(x))
        ]))
    return valid_candidates[:final_k]


dialects = ['atticionic', 'doric', 'northwest', 'aeolic']
max_l = max(len(i['masked_gt']) for i in test_set) 

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc1 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
c1 = 0
c2 = 0
res = []
for inscription in tqdm(test_set):
    ground_truth = inscription['masked_gt']
    masked = inscription['masked_ag']
    dialect = inscription['dialect']
    gt_len = len(ground_truth)

    gt_tokens = tokenizer.tokenize(ground_truth)
    num_tokens = len(gt_tokens)

    multi_mask_str = " ".join(["[MASK]"] * num_tokens)
    masked_query = masked.replace("[MASK]", multi_mask_str)

    masked_query = masked.replace("[MASK]", "<mask>")
    inference_result = fill_mask(masked_query)

    top_20_words = []
    
    if num_tokens == 1: # If the word is made of just one token (simple case)
        # clean_candidates = [
        #     x['token_str'] for x in inference_result 
        #     if not x['token_str'].startswith("##") 
        #     and "-" not in x['token_str']
        #     and len(x['token_str']) == gt_len
        # ]
        clean_candidates = list(dict.fromkeys([
            strip_accents(x['token_str'].lower())
            for x in inference_result 
            if len(x['token_str'].replace(' ', '')) == len(ground_truth)
            and strict_greek_pattern.match(strip_accents(x['token_str']))
        ]))
        top_20_words = clean_candidates[:20]
        res.append((0, masked, ground_truth, top_20_words))
        if len(top_20_words) != 20:
            c1 += 1
    else: # If the word is made of multiple tokens (beam search)
        top_20_words = beam_search(inference_result, gt_len, final_k=20)
        res.append((1, masked, ground_truth, top_20_words))
    
        if len(top_20_words) != 20:
            c2 += 1

    found_in_top1 = False
    found_in_top20 = False
    
    if top_20_words:
        if top_20_words[0] == ground_truth:
            found_in_top1 = True
        if ground_truth in top_20_words:
            found_in_top20 = True

    if dialect in acc1 and gt_len in acc1[dialect]:
        acc1[dialect][gt_len].append(1 if found_in_top1 else 0)
        acc20[dialect][gt_len].append(1 if found_in_top20 else 0)
    
    if len(top_20_words) > 0:
        editd[dialect][gt_len].append(editdistance.eval(top_20_words[0], ground_truth) / gt_len)
    else:
        editd[dialect][gt_len].append(1.0)

for dialect in dialects:
    print(f"======== {dialect} ========")
    print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
    print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')
    
print(f"======== TOTAL ========")
acc1t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc1.items():
    for kk, v in vs.items():
        acc1t[kk].extend(v)

acc20t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc20.items():
    for kk, v in vs.items():
        acc20t[kk].extend(v)

cert = { x: [] for x in range(1, max_l+1)}
for k, vs in editd.items():
    for kk, v in vs.items():
        cert[kk].extend(v)
        
print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

print(c1, c2, c1+c2)

Device set to use cuda:0
100%|██████████| 95/95 [00:33<00:00,  2.84it/s]

======== atticionic ========
CER  : 87.60%
ACC1 : 1.28%
ACC20: 21.15%
======== doric ========
CER  : 89.14%
ACC1 : 0.00%
ACC20: 10.00%
======== northwest ========
CER  : 85.00%
ACC1 : 10.00%
ACC20: 50.00%
======== aeolic ========
CER  : 89.17%
ACC1 : 0.00%
ACC20: 0.00%
======== TOTAL ========
CER : 87.67%
ACC1 : 1.74%
ACC20 : 17.31%
2 30 32

### GreTa (T5)
"bowphs/GreTa"

In [22]:
import unicodedata

def strip_accents(s):
  return ''.join(
      c for c in unicodedata.normalize('NFD', s)
      if unicodedata.category(c) != 'Mn')

In [50]:
import torch
import numpy as np
import editdistance
from tqdm import tqdm
from transformers import T5Tokenizer, T5ForConditionalGeneration
import re

greek_pattern = re.compile(r"^[\u0370-\u03FF\u1F00-\u1FFF]+$")

model_name = "bowphs/GreTa"
device = "cuda" if torch.cuda.is_available() else "cpu"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name).to(device)
model.eval()

def t5_fill_mask(masked_text, top_k=3500):
    t5_input = masked_text.replace("[MASK]", "<extra_id_0>")
    
    inputs = tokenizer(t5_input, return_tensors="pt").to(device)
    
    # Prepare the decoder input. 
    # We want T5 to start generating from the first sentinel.
    # The standard start sequence for filling <extra_id_0> is: <pad> <extra_id_0>
    decoder_input_ids = tokenizer("<pad> <extra_id_0>", return_tensors="pt", add_special_tokens=False).input_ids.to(device)

    with torch.no_grad():
        outputs = model(input_ids=inputs.input_ids, decoder_input_ids=decoder_input_ids)


    next_token_logits = outputs.logits[0, -1, :]
    probs = torch.softmax(next_token_logits, dim=-1)
    top_k_probs, top_k_ids = torch.topk(probs, top_k)
    
    results = []
    for score, token_id in zip(top_k_probs, top_k_ids):
        token_str = tokenizer.decode(token_id).replace(" ", "").strip()
        
        # Skip empty strings or special tokens if necessary
        if not token_str: continue
        
        results.append({"token_str": token_str, "score": score.item()})
        
    return results


max_l = 20 
dialects = set(inscription['dialect'] for inscription in test_set)

ctop1s = []
ctop20s = []

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc1 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}

pbar = tqdm(test_set)

res = []
for inscription in pbar:
    ground_truth = inscription['masked_gt']
    masked = inscription['masked_ag']
    dialect = inscription['dialect']
    

    inference_result = t5_fill_mask(masked, top_k=3500)

    # constr = [ strip_accents(x['token_str']) for x in inference_result if len(x['token_str']) == len(ground_truth)][:20]
    constr = list(dict.fromkeys([
    strip_accents(x['token_str']) 
    for x in inference_result 
    if len(x['token_str']) == len(ground_truth)
    and not x['token_str'].startswith("<extra_id_")
    and greek_pattern.match(strip_accents(x['token_str']))
    ]))[:20]

    ctop1 = 0
    ctop20 = 0
    
    if constr and ground_truth == constr[0]:
        ctop1 = 1
        ctop20 = 1
    
    elif ground_truth in [x for x in constr]:
        ctop20 = 1

    ctop1s.append(ctop1)
    ctop20s.append(ctop20)
    
    gt_len = len(ground_truth)
    if gt_len in acc1[dialect]:
        acc1[dialect][gt_len].append(ctop1)
        acc20[dialect][gt_len].append(ctop20)

        if constr:
            score = editdistance.eval(constr[0], ground_truth) / len(ground_truth)
            editd[dialect][gt_len].append(score)
        else:
            editd[dialect][gt_len].append(1.0)
    res.append((masked, ground_truth, constr))

for dialect in dialects:
    print(f"======== {dialect} ========")
    cer_vals = [np.mean(v) for v in editd[dialect].values() if v]
    acc1_vals = [np.mean(v) for v in acc1[dialect].values() if v]
    acc20_vals = [np.mean(v) for v in acc20[dialect].values() if v]
    
    print(f'CER  : {np.mean(cer_vals)*100:.2f}%' if cer_vals else 'CER  : N/A')
    print(f'ACC1 : {np.mean(acc1_vals)*100:.2f}%' if acc1_vals else 'ACC1 : N/A')
    print(f'ACC20: {np.mean(acc20_vals)*100:.2f}%' if acc20_vals else 'ACC20: N/A')

print(f"======== TOTAL ========")
cert = [val for sublist in editd.values() for v in sublist.values() for val in v]
acc1t = [val for sublist in acc1.values() for v in sublist.values() for val in v]
acc20t = [val for sublist in acc20.values() for v in sublist.values() for val in v]

print(f'CER : {np.mean(cert)*100:.2f}%' if cert else 'CER : N/A')
print(f'ACC1 : {np.mean(acc1t)*100:.2f}%' if acc1t else 'ACC1 : N/A')
print(f'ACC20 : {np.mean(acc20t)*100:.2f}%' if acc20t else 'ACC20 : N/A')

100%|██████████| 95/95 [00:19<00:00,  4.85it/s]

======== atticionic ========
CER  : 85.17%
ACC1 : 1.28%
ACC20: 17.31%
======== northwest ========
CER  : 57.50%
ACC1 : 30.00%
ACC20: 50.00%
======== doric ========
CER  : 92.96%
ACC1 : 0.00%
ACC20: 25.00%
======== aeolic ========
CER  : 95.83%
ACC1 : 0.00%
ACC20: 0.00%
======== TOTAL ========
CER : 85.62%
ACC1 : 3.16%
ACC20 : 17.89%

### PhilTa (T5)
"bowphs/PhilTa"

In [48]:
import torch
import numpy as np
import editdistance
from tqdm import tqdm
from transformers import T5Tokenizer, T5ForConditionalGeneration
import re

greek_pattern = re.compile(r"^[\u0370-\u03FF\u1F00-\u1FFF]+$")

model_name = "bowphs/PhilTa"
device = "cuda" if torch.cuda.is_available() else "cpu"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name).to(device)
model.eval()

def t5_fill_mask(masked_text, top_k=3500):
    t5_input = masked_text.replace("[MASK]", "<extra_id_0>")
    
    inputs = tokenizer(t5_input, return_tensors="pt").to(device)
    
    # Prepare the decoder input. 
    # We want T5 to start generating from the first sentinel.
    # The standard start sequence for filling <extra_id_0> is: <pad> <extra_id_0>
    decoder_input_ids = tokenizer("<pad> <extra_id_0>", return_tensors="pt", add_special_tokens=False).input_ids.to(device)

    with torch.no_grad():
        outputs = model(input_ids=inputs.input_ids, decoder_input_ids=decoder_input_ids)


    next_token_logits = outputs.logits[0, -1, :]
    probs = torch.softmax(next_token_logits, dim=-1)
    top_k_probs, top_k_ids = torch.topk(probs, top_k)
    
    results = []
    for score, token_id in zip(top_k_probs, top_k_ids):
        token_str = tokenizer.decode(token_id).replace(" ", "").strip()
        
        # Skip empty strings or special tokens if necessary
        if not token_str: continue
        
        results.append({"token_str": token_str, "score": score.item()})
        
    return results


max_l = 20 
dialects = set(inscription['dialect'] for inscription in test_set)

ctop1s = []
ctop20s = []

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc1 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}

pbar = tqdm(test_set)

res = []
for inscription in pbar:
    ground_truth = inscription['masked_gt']
    masked = inscription['masked_ag']
    dialect = inscription['dialect']
    

    inference_result = t5_fill_mask(masked, top_k=3500)

    # constr = [ strip_accents(x['token_str']) for x in inference_result if len(x['token_str']) == len(ground_truth)][:20]
    constr = list(dict.fromkeys([
    strip_accents(x['token_str']) 
    for x in inference_result 
    if len(x['token_str']) == len(ground_truth)
    and not x['token_str'].startswith("<extra_id_")
    and greek_pattern.match(strip_accents(x['token_str']))
    ]))[:20]

    ctop1 = 0
    ctop20 = 0
    
    if constr and ground_truth == constr[0]:
        ctop1 = 1
        ctop20 = 1
    
    elif ground_truth in [x for x in constr]:
        ctop20 = 1

    ctop1s.append(ctop1)
    ctop20s.append(ctop20)
    
    gt_len = len(ground_truth)
    if gt_len in acc1[dialect]:
        acc1[dialect][gt_len].append(ctop1)
        acc20[dialect][gt_len].append(ctop20)

        if constr:
            score = editdistance.eval(constr[0], ground_truth) / len(ground_truth)
            editd[dialect][gt_len].append(score)
        else:
            editd[dialect][gt_len].append(1.0)
    res.append((masked, ground_truth, constr))

for dialect in dialects:
    print(f"======== {dialect} ========")
    cer_vals = [np.mean(v) for v in editd[dialect].values() if v]
    acc1_vals = [np.mean(v) for v in acc1[dialect].values() if v]
    acc20_vals = [np.mean(v) for v in acc20[dialect].values() if v]
    
    print(f'CER  : {np.mean(cer_vals)*100:.2f}%' if cer_vals else 'CER  : N/A')
    print(f'ACC1 : {np.mean(acc1_vals)*100:.2f}%' if acc1_vals else 'ACC1 : N/A')
    print(f'ACC20: {np.mean(acc20_vals)*100:.2f}%' if acc20_vals else 'ACC20: N/A')

print(f"======== TOTAL ========")
cert = [val for sublist in editd.values() for v in sublist.values() for val in v]
acc1t = [val for sublist in acc1.values() for v in sublist.values() for val in v]
acc20t = [val for sublist in acc20.values() for v in sublist.values() for val in v]

print(f'CER : {np.mean(cert)*100:.2f}%' if cert else 'CER : N/A')
print(f'ACC1 : {np.mean(acc1t)*100:.2f}%' if acc1t else 'ACC1 : N/A')
print(f'ACC20 : {np.mean(acc20t)*100:.2f}%' if acc20t else 'ACC20 : N/A')

100%|██████████| 95/95 [00:18<00:00,  5.13it/s]

======== atticionic ========
CER  : 78.24%
ACC1 : 11.54%
ACC20: 18.41%
======== northwest ========
CER  : 85.83%
ACC1 : 10.00%
ACC20: 30.00%
======== doric ========
CER  : 89.00%
ACC1 : 0.00%
ACC20: 10.00%
======== aeolic ========
CER  : 91.67%
ACC1 : 0.00%
ACC20: 0.00%
======== TOTAL ========
CER : 81.42%
ACC1 : 7.37%
ACC20 : 14.74%

### Epigr_3_Llama-3.1-8B-Instruct

In [2]:
import json
from transformers import pipeline, AutoTokenizer, LlamaForCausalLM, AutoModelForCausalLM
from accelerate import init_empty_weights, load_checkpoint_and_dispatch
import torch
import warnings
warnings.filterwarnings("ignore", message=".*copying from a non-meta parameter in the checkpoint*")
model_id = "Ericu950/Epigr_3_Llama-3.1-8B-Instruct_text"

with init_empty_weights():
    model = LlamaForCausalLM.from_pretrained(model_id)

model = LlamaForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
    torch_dtype=torch.float16, # Recommended for Llama to save memory
    offload_folder="offload"
)

tokenizer = AutoTokenizer.from_pretrained(model_id)

generation_pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    device_map="auto",
)

Loading checkpoint shards: 100%|██████████| 4/4 [00:03<00:00,  1.16it/s]
`torch_dtype` is deprecated! Use `dtype` instead!
Loading checkpoint shards: 100%|██████████| 4/4 [00:01<00:00,  2.07it/s]
Device set to use cuda:0

In [ ]:
inscription_edition = "----εκτηι ισταμενου· ευμολποσ μολπου επεστατει· πρυτανεων γνωμη μεσσηνεωσ του διονοσ κατασταθεντοσ υπο --—ου του μυγαλου ερμωνοσ του μυιστρου κατασταθεντοσ υπο --—ρατου του προμαχου μολπου του μολπου λεοντοσ του -—ιππου κατασταθεντοσ υπο αριστοφανου του νουμηνιου του στησιοχου ηρακλειτου του αρτεμιδωρου δημοφωντοσ του πρυτανιοσ δαμωνοσ του ονφαλιωνοσ· επειδη οι δικασται οι αποσταλεντεσ εισ καλυμναν κομιζουσιν ψηφισμα παρα του δημου του καλυμνιων εν ωι γεγραπται οτι ο δημοσ ο καλυμνιων στεφανοι τον δημον χρυσωι στεφανωι αρετησ ενεκεν και ευνοιασ τησ εισ αυτον στεφανοι δε και τουσ δικαστασ τουσ αποσταλεντασ χρυσωι στεφανωι καλοκαγαθιασ ενεκεν κλεανδρον διοδωρου λεοντα ευβουλου κεφαλον δρακοντοσ θεοδωρον νουμηνιου λεοντα δρακοντιδου και περι τουτων οιεται δειν επιμελειαν ποιησασθαι τον δημον οπωσ ο τησ πολεωσ στεφανοσ αναγορευθηι και ο των δικαστων εν τωι θεατρωι διονυσιοισ δεδοχθαι τωι δημωι· τον μεν αγωνοθετην αναγγειλαι τον τησ πολεωσ στεφανον και τον των δικαστων κυκλιων τηι πρωτηι· επηιν[7 missing letters] και τουσ δικαστασ τουσ αποσταλεντασ επειδη αξιοι γενομενοι του δημου τιμασ περιεποιησαν τηι πολει·"
system_prompt = "Fill in the missing letters in this inscription!"
input_messages = [
    {"role": "system", "content": system_prompt},
    {"role": "user", "content": inscription_edition},
]
terminators = [
    tokenizer.eos_token_id,
    tokenizer.convert_tokens_to_ids("<|eot_id|>")
]
outputs = generation_pipeline(
    input_messages,
    max_new_tokens=10,
    num_beams=30, # Set this as high as your memory will allow!
    num_return_sequences=10,
    early_stopping=True,
)
beam_contents = []
for output in outputs:
    generated_text = output.get('generated_text', [])
    for item in generated_text:
        if item.get('role') == 'assistant':
            beam_contents.append(item.get('content'))
real_response = "ησθαι δε"
print(f"The masked sequence: {real_response}")
for i, content in enumerate(beam_contents, start=1):
    print(f"Suggestion {i}: {content}")

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

The masked sequence: ησθαι δε
Suggestion 1: ησθαι δε
Suggestion 2: εσθαι δε
Suggestion 3: ησθωσ δε
Suggestion 4: ησθωσαν
Suggestion 5: εισθαι δ
Suggestion 6: ησθωι δε
Suggestion 7: εσθωσ δε
Suggestion 8: εσθωι δε
Suggestion 9: εσθωσαν
Suggestion 10: ησεν δε 0

In [ ]:
ctop1s = []
ctop20s = []

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}

acc1 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}

pbar = tqdm(test_set)
for inscription in pbar:
    ground_truth = inscription['masked_gt']
    
    masked = inscription['masked_ag'].replace('[MASK]', f"[{len(ground_truth)} missing letters]" )

    dialect = inscription['dialect']
    
    system_prompt = "Fill in the missing letters in this inscription!"
    input_messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": masked},
    ]
    terminators = [
        tokenizer.eos_token_id,
        tokenizer.convert_tokens_to_ids("<|eot_id|>")
    ]
    outputs = generation_pipeline(
        input_messages,
        max_new_tokens=10,
        num_beams=30, # Set this as high as your memory will allow!
        num_return_sequences=20,
        early_stopping=True,
    )
    constr = []
    for output in outputs:
        generated_text = output.get('generated_text', [])
        for item in generated_text:
            if item.get('role') == 'assistant':
                constr.append(item.get('content'))


    ctop1 = 0
    ctop20 = 0
    if ground_truth in [ x for x in constr[:1] ]:
        ctop1 = 1
        ctop20 = 1
    if ground_truth in [ x for x in constr ]:
        ctop20 = 1

    ctop1s.append(ctop1)
    ctop20s.append(ctop20)
    acc1[dialect][len(ground_truth)].append(ctop1)
    acc20[dialect][len(ground_truth)].append(ctop20)

    if constr != []:
        editd[dialect][len(ground_truth)].append(editdistance.eval(constr[0], ground_truth) / len(ground_truth))
    else:
        editd[dialect][len(ground_truth)].append(1.0)

for dialect in dialects:
    print(f"======== {dialect} ========")
    print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
    print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')

print(f"======== TOTAL ========")
cert = { x: [] for x in range(1, max_l+1)}
for k, vs in editd.items():
    for kk, v in vs.items():
        cert[kk].extend(v)
acc1t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc1.items():
    for kk, v in vs.items():
        acc1t[kk].extend(v)

acc20t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc20.items():
    for kk, v in vs.items():
        acc20t[kk].extend(v)
print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

  0%|          | 0/95 [00:00<?, ?it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 1/95 [00:00<00:38,  2.44it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 2/95 [00:00<00:31,  2.98it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 3/95 [00:01<00:36,  2.55it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▍         | 4/95 [00:01<00:36,  2.52it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  5%|▌         | 5/95 [00:01<00:35,  2.52it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  6%|▋         | 6/95 [00:02<00:36,  2.42it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  7%|▋         | 7/95 [00:02<00:36,  2.43it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  8%|▊         | 8/95 [00:03<00:34,  2.53it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  9%|▉         | 9/95 [00:03<00:35,  2.40it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 11%|█         | 10/95 [00:04<00:36,  2.36it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 12%|█▏        | 11/95 [00:04<00:39,  2.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 13%|█▎        | 12/95 [00:05<00:42,  1.95it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 14%|█▎        | 13/95 [00:05<00:39,  2.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 15%|█▍        | 14/95 [00:06<00:37,  2.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 16%|█▌        | 15/95 [00:06<00:33,  2.39it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 17%|█▋        | 16/95 [00:06<00:33,  2.33it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 18%|█▊        | 17/95 [00:07<00:30,  2.56it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 19%|█▉        | 18/95 [00:07<00:29,  2.59it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 20%|██        | 19/95 [00:07<00:30,  2.50it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 21%|██        | 20/95 [00:08<00:32,  2.29it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 22%|██▏       | 21/95 [00:09<00:36,  2.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 23%|██▎       | 22/95 [00:09<00:36,  2.02it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 24%|██▍       | 23/95 [00:10<00:35,  2.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 25%|██▌       | 24/95 [00:10<00:32,  2.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 26%|██▋       | 25/95 [00:10<00:30,  2.30it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 27%|██▋       | 26/95 [00:11<00:28,  2.40it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 28%|██▊       | 27/95 [00:11<00:27,  2.46it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 29%|██▉       | 28/95 [00:12<00:29,  2.31it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 31%|███       | 29/95 [00:12<00:28,  2.31it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 32%|███▏      | 30/95 [00:13<00:30,  2.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 33%|███▎      | 31/95 [00:13<00:27,  2.37it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 34%|███▎      | 32/95 [00:13<00:27,  2.31it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 35%|███▍      | 33/95 [00:14<00:28,  2.21it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 36%|███▌      | 34/95 [00:14<00:24,  2.45it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 37%|███▋      | 35/95 [00:15<00:24,  2.41it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 38%|███▊      | 36/95 [00:15<00:25,  2.36it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 39%|███▉      | 37/95 [00:16<00:28,  2.02it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 40%|████      | 38/95 [00:16<00:25,  2.22it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 41%|████      | 39/95 [00:16<00:22,  2.45it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 42%|████▏     | 40/95 [00:17<00:29,  1.86it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 43%|████▎     | 41/95 [00:18<00:27,  2.00it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 44%|████▍     | 42/95 [00:18<00:25,  2.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 45%|████▌     | 43/95 [00:19<00:26,  2.00it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 46%|████▋     | 44/95 [00:19<00:22,  2.26it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 47%|████▋     | 45/95 [00:19<00:21,  2.29it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 48%|████▊     | 46/95 [00:20<00:21,  2.33it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 49%|████▉     | 47/95 [00:20<00:22,  2.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 51%|█████     | 48/95 [00:21<00:21,  2.21it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 52%|█████▏    | 49/95 [00:21<00:21,  2.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 53%|█████▎    | 50/95 [00:22<00:19,  2.31it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 54%|█████▎    | 51/95 [00:22<00:18,  2.34it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 55%|█████▍    | 52/95 [00:22<00:17,  2.41it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 56%|█████▌    | 53/95 [00:23<00:20,  2.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 57%|█████▋    | 54/95 [00:23<00:18,  2.23it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 58%|█████▊    | 55/95 [00:24<00:17,  2.28it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 59%|█████▉    | 56/95 [00:24<00:17,  2.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 60%|██████    | 57/95 [00:25<00:17,  2.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 61%|██████    | 58/95 [00:25<00:15,  2.34it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 62%|██████▏   | 59/95 [00:25<00:13,  2.58it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 63%|██████▎   | 60/95 [00:26<00:12,  2.79it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 64%|██████▍   | 61/95 [00:26<00:15,  2.23it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 65%|██████▌   | 62/95 [00:27<00:16,  2.01it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 66%|██████▋   | 63/95 [00:28<00:16,  1.89it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 67%|██████▋   | 64/95 [00:28<00:15,  1.97it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 68%|██████▊   | 65/95 [00:28<00:13,  2.21it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 69%|██████▉   | 66/95 [00:29<00:12,  2.25it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 71%|███████   | 67/95 [00:29<00:12,  2.27it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 72%|███████▏  | 68/95 [00:30<00:11,  2.38it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 73%|███████▎  | 69/95 [00:31<00:16,  1.58it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 74%|███████▎  | 70/95 [00:31<00:14,  1.77it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 75%|███████▍  | 71/95 [00:32<00:14,  1.70it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 76%|███████▌  | 72/95 [00:32<00:12,  1.81it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 77%|███████▋  | 73/95 [00:33<00:10,  2.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 78%|███████▊  | 74/95 [00:33<00:10,  2.02it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 79%|███████▉  | 75/95 [00:33<00:09,  2.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 80%|████████  | 76/95 [00:34<00:08,  2.36it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 81%|████████  | 77/95 [00:34<00:07,  2.25it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 82%|████████▏ | 78/95 [00:35<00:07,  2.24it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 83%|████████▎ | 79/95 [00:36<00:08,  1.82it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 84%|████████▍ | 80/95 [00:36<00:06,  2.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 85%|████████▌ | 81/95 [00:36<00:06,  2.21it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 86%|████████▋ | 82/95 [00:37<00:05,  2.23it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 87%|████████▋ | 83/95 [00:37<00:05,  2.35it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 88%|████████▊ | 84/95 [00:37<00:04,  2.35it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 89%|████████▉ | 85/95 [00:38<00:04,  2.31it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 91%|█████████ | 86/95 [00:38<00:03,  2.29it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 92%|█████████▏| 87/95 [00:39<00:03,  2.36it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 93%|█████████▎| 88/95 [00:39<00:02,  2.40it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 94%|█████████▎| 89/95 [00:40<00:02,  2.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 95%|█████████▍| 90/95 [00:40<00:02,  2.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 96%|█████████▌| 91/95 [00:41<00:01,  2.17it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 97%|█████████▋| 92/95 [00:41<00:01,  2.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 98%|█████████▊| 93/95 [00:41<00:00,  2.36it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 99%|█████████▉| 94/95 [00:42<00:00,  2.60it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
100%|██████████| 95/95 [00:42<00:00,  2.22it/s]

======== atticionic ========
CER  : 39.08%
ACC1 : 44.69%
ACC20: 58.69%
======== doric ========
CER  : 63.95%
ACC1 : 27.50%
ACC20: 47.50%
======== northwest ========
CER  : 59.17%
ACC1 : 30.00%
ACC20: 50.00%
======== aeolic ========
CER  : 60.00%
ACC1 : 33.33%
ACC20: 33.33%
======== TOTAL ========
CER : 48.77%
ACC1 : 37.80%
ACC20 : 52.59%

### Logion Fine Tune

In [5]:
import re

greek_pattern = re.compile(r"^[\u0370-\u03FF\u1F00-\u1FFF]+$")

model_name = "./models/logion-epi-agBERT"
fill_mask = pipeline("fill-mask", model=model_name, tokenizer=model_name, top_k=3500)

ctop1s = []
ctop20s = []

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}

acc1 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}

pbar = tqdm(test_set)
res = []
for inscription in pbar:
    ground_truth = inscription['masked_gt']
    masked = inscription['masked_ag']

    dialect = inscription['dialect']
    
    inference_result = fill_mask(masked)

    # constr = [ x for x in inference_result if len(x['token_str']) == len(ground_truth)][:20]
    # constr = [
    #         strip_accents(x) for x in inference_result 
    #         if not x['token_str'].startswith("##") 
    #         and "-" not in x['token_str']
    #         and len(x['token_str']) == len(ground_truth)
    #         and greek_pattern.match(strip_accents(x['token_str']))
    #     ][:20]

    constr = list(dict.fromkeys([
    strip_accents(x['token_str']) 
    for x in inference_result 
    if len(x['token_str']) == len(ground_truth)
    and not x['token_str'].startswith("<extra_id_")
    and greek_pattern.match(strip_accents(x['token_str']))
    ]))[:20]
    
    res.append((masked, ground_truth, constr))

    ctop1 = 0
    ctop20 = 0
    if ground_truth in [ x for x in constr[:1] ]:
        ctop1 = 1
        ctop20 = 1
    if ground_truth in [ x for x in constr ]:
        ctop20 = 1

    ctop1s.append(ctop1)
    ctop20s.append(ctop20)
    acc1[dialect][len(ground_truth)].append(ctop1)
    acc20[dialect][len(ground_truth)].append(ctop20)

    if constr != []:
        editd[dialect][len(ground_truth)].append(editdistance.eval(strip_accents(constr[0]), ground_truth) / len(ground_truth))
    else:
        editd[dialect][len(ground_truth)].append(1.0)

for dialect in dialects:
    print(f"======== {dialect} ========")
    print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
    print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')

print(f"======== TOTAL ========")
cert = { x: [] for x in range(1, max_l+1)}
for k, vs in editd.items():
    for kk, v in vs.items():
        cert[kk].extend(v)
acc1t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc1.items():
    for kk, v in vs.items():
        acc1t[kk].extend(v)

acc20t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc20.items():
    for kk, v in vs.items():
        acc20t[kk].extend(v)
print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

Device set to use cuda:0
 11%|█         | 10/95 [00:02<00:22,  3.84it/s]You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
100%|██████████| 95/95 [00:25<00:00,  3.74it/s]

======== atticionic ========
CER  : 57.90%
ACC1 : 26.61%
ACC20: 33.75%
======== doric ========
CER  : 75.86%
ACC1 : 10.00%
ACC20: 42.50%
======== northwest ========
CER  : 50.83%
ACC1 : 40.00%
ACC20: 50.00%
======== aeolic ========
CER  : 64.17%
ACC1 : 0.00%
ACC20: 0.00%
======== TOTAL ========
CER : 65.03%
ACC1 : 19.98%
ACC20 : 31.76%

In [6]:
from transformers import pipeline, AutoTokenizer
from tqdm import tqdm
import math

model_name = "./models/logion-epi-agBERT"
tokenizer = AutoTokenizer.from_pretrained(model_name)

fill_mask = pipeline("fill-mask", model=model_name, tokenizer=tokenizer, top_k=1000)

def beam_search(inference_result, target_length, final_k=20):
    search_width = 1500
    beam = [(0.0, [])] 
    
    for mask_pos_candidates in inference_result:
        new_beam = []
        for current_score, current_tokens in beam:
            for candidate in mask_pos_candidates:
                token_str = candidate['token_str']
                if "-" in token_str:
                    continue
                score = candidate['score']
                
                new_score = current_score + math.log(score if score > 0 else 1e-10)
                new_tokens = current_tokens + [token_str]
                new_beam.append((new_score, new_tokens))

        new_beam.sort(key=lambda x: x[0], reverse=True)
        beam = new_beam[:search_width]
    
    valid_candidates = []
    for _, tokens in beam:
        word = "".join(tokens).replace("##", "")
        if len(word) == target_length:
            valid_candidates.append(word)
            
    return [x for x in valid_candidates if greek_pattern.match(x)][:final_k]


dialects = ['atticionic', 'doric', 'northwest', 'aeolic']
max_l = max(len(i['masked_gt']) for i in test_set) 

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc1 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
c1 = 0
c2 = 0
res = []
for inscription in tqdm(test_set):
    ground_truth = inscription['masked_gt']
    masked = inscription['masked_ag']
    dialect = inscription['dialect']
    gt_len = len(ground_truth)

    gt_tokens = tokenizer.tokenize(ground_truth)
    num_tokens = len(gt_tokens)

    multi_mask_str = " ".join(["[MASK]"] * num_tokens)
    masked_query = masked.replace("[MASK]", multi_mask_str)

    inference_result = fill_mask(masked_query)

    top_20_words = []
    
    if num_tokens == 1: # If the word is made of just one token (simple case)

        clean_candidates = list(dict.fromkeys([
            x['token_str'] 
            for x in inference_result 
            if len(x['token_str']) == len(ground_truth)
            and not x['token_str'].startswith("<extra_id_")
            and greek_pattern.match(x['token_str'])
        ]))
        
        top_20_words = clean_candidates[:20]
        res.append((0, masked, ground_truth, top_20_words))
        if len(top_20_words) != 20:
            c1 += 1
    else: # If the word is made of multiple tokens (beam search)
        top_20_words = beam_search(inference_result, gt_len, final_k=20)
        res.append((1, masked, ground_truth, top_20_words))
    
        if len(top_20_words) != 20:
            c2 += 1

    found_in_top1 = False
    found_in_top20 = False
    
    if top_20_words:
        if top_20_words[0] == ground_truth:
            found_in_top1 = True
        if ground_truth in top_20_words:
            found_in_top20 = True

    if dialect in acc1 and gt_len in acc1[dialect]:
        acc1[dialect][gt_len].append(1 if found_in_top1 else 0)
        acc20[dialect][gt_len].append(1 if found_in_top20 else 0)
    
    if len(top_20_words) > 0:
        editd[dialect][gt_len].append(editdistance.eval(top_20_words[0], ground_truth) / gt_len)
    else:
        editd[dialect][gt_len].append(1.0)
    

for dialect in dialects:
    print(f"======== {dialect} ========")
    print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
    print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')
    
print(f"======== TOTAL ========")
acc1t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc1.items():
    for kk, v in vs.items():
        acc1t[kk].extend(v)

acc20t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc20.items():
    for kk, v in vs.items():
        acc20t[kk].extend(v)

cert = { x: [] for x in range(1, max_l+1)}
for k, vs in editd.items():
    for kk, v in vs.items():
        cert[kk].extend(v)
        
print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

print(c1, c2, c1+c2)

Device set to use cuda:0
100%|██████████| 95/95 [03:11<00:00,  2.01s/it]

======== atticionic ========
CER  : 62.70%
ACC1 : 27.57%
ACC20: 36.12%
======== doric ========
CER  : 74.77%
ACC1 : 12.50%
ACC20: 47.50%
======== northwest ========
CER  : 53.33%
ACC1 : 40.00%
ACC20: 50.00%
======== aeolic ========
CER  : 51.67%
ACC1 : 33.33%
ACC20: 33.33%
======== TOTAL ========
CER : 67.73%
ACC1 : 21.38%
ACC20 : 34.56%
4 13 17

In [7]:
import re

greek_pattern = re.compile(r"^[\u0370-\u03FF\u1F00-\u1FFF]+$")

model_name = "./models/logion-archaic"
fill_mask = pipeline("fill-mask", model=model_name, tokenizer=model_name, top_k=3500)

ctop1s = []
ctop20s = []

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}

acc1 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}

pbar = tqdm(test_set)
res = []
for inscription in pbar:
    ground_truth = inscription['masked_gt']
    masked = inscription['masked_ag']

    dialect = inscription['dialect']
    
    inference_result = fill_mask(masked)

    # constr = [ x for x in inference_result if len(x['token_str']) == len(ground_truth)][:20]
    # constr = [
    #         strip_accents(x) for x in inference_result 
    #         if not x['token_str'].startswith("##") 
    #         and "-" not in x['token_str']
    #         and len(x['token_str']) == len(ground_truth)
    #         and greek_pattern.match(strip_accents(x['token_str']))
    #     ][:20]

    constr = list(dict.fromkeys([
    strip_accents(x['token_str']) 
    for x in inference_result 
    if len(x['token_str']) == len(ground_truth)
    and not x['token_str'].startswith("<extra_id_")
    and greek_pattern.match(strip_accents(x['token_str']))
    ]))[:20]
    
    res.append((masked, ground_truth, constr))

    ctop1 = 0
    ctop20 = 0
    if ground_truth in [ x for x in constr[:1] ]:
        ctop1 = 1
        ctop20 = 1
    if ground_truth in [ x for x in constr ]:
        ctop20 = 1

    ctop1s.append(ctop1)
    ctop20s.append(ctop20)
    acc1[dialect][len(ground_truth)].append(ctop1)
    acc20[dialect][len(ground_truth)].append(ctop20)

    if constr != []:
        editd[dialect][len(ground_truth)].append(editdistance.eval(strip_accents(constr[0]), ground_truth) / len(ground_truth))
    else:
        editd[dialect][len(ground_truth)].append(1.0)

for dialect in dialects:
    print(f"======== {dialect} ========")
    print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
    print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')

print(f"======== TOTAL ========")
cert = { x: [] for x in range(1, max_l+1)}
for k, vs in editd.items():
    for kk, v in vs.items():
        cert[kk].extend(v)
acc1t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc1.items():
    for kk, v in vs.items():
        acc1t[kk].extend(v)

acc20t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc20.items():
    for kk, v in vs.items():
        acc20t[kk].extend(v)
print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

Device set to use cuda:0
100%|██████████| 95/95 [00:25<00:00,  3.78it/s]

======== atticionic ========
CER  : 57.65%
ACC1 : 26.88%
ACC20: 34.06%
======== doric ========
CER  : 65.58%
ACC1 : 15.00%
ACC20: 37.50%
======== northwest ========
CER  : 78.33%
ACC1 : 10.00%
ACC20: 60.00%
======== aeolic ========
CER  : 70.83%
ACC1 : 0.00%
ACC20: 0.00%
======== TOTAL ========
CER : 65.75%
ACC1 : 19.18%
ACC20 : 31.85%

Logion (beam search)

In [8]:
from transformers import pipeline, AutoTokenizer
from tqdm import tqdm
import math

model_name = "./models/logion-archaic"
tokenizer = AutoTokenizer.from_pretrained(model_name)

fill_mask = pipeline("fill-mask", model=model_name, tokenizer=tokenizer, top_k=1000)

def beam_search(inference_result, target_length, final_k=20):
    search_width = 1500
    beam = [(0.0, [])] 
    
    for mask_pos_candidates in inference_result:
        new_beam = []
        for current_score, current_tokens in beam:
            for candidate in mask_pos_candidates:
                token_str = candidate['token_str']
                if "-" in token_str:
                    continue
                score = candidate['score']
                
                new_score = current_score + math.log(score if score > 0 else 1e-10)
                new_tokens = current_tokens + [token_str]
                new_beam.append((new_score, new_tokens))

        new_beam.sort(key=lambda x: x[0], reverse=True)
        beam = new_beam[:search_width]
    
    valid_candidates = []
    for _, tokens in beam:
        word = "".join(tokens).replace("##", "")
        if len(word) == target_length:
            valid_candidates.append(word)
            
    return [x for x in valid_candidates if greek_pattern.match(x)][:final_k]


dialects = ['atticionic', 'doric', 'northwest', 'aeolic']
max_l = max(len(i['masked_gt']) for i in test_set) 

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc1 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
c1 = 0
c2 = 0
res = []
for inscription in tqdm(test_set):
    ground_truth = inscription['masked_gt']
    masked = inscription['masked_ag']
    dialect = inscription['dialect']
    gt_len = len(ground_truth)

    gt_tokens = tokenizer.tokenize(ground_truth)
    num_tokens = len(gt_tokens)

    multi_mask_str = " ".join(["[MASK]"] * num_tokens)
    masked_query = masked.replace("[MASK]", multi_mask_str)

    inference_result = fill_mask(masked_query)

    top_20_words = []
    
    if num_tokens == 1: # If the word is made of just one token (simple case)

        clean_candidates = list(dict.fromkeys([
            x['token_str'] 
            for x in inference_result 
            if len(x['token_str']) == len(ground_truth)
            and not x['token_str'].startswith("<extra_id_")
            and greek_pattern.match(x['token_str'])
        ]))
        
        top_20_words = clean_candidates[:20]
        res.append((0, masked, ground_truth, top_20_words))
        if len(top_20_words) != 20:
            c1 += 1
    else: # If the word is made of multiple tokens (beam search)
        top_20_words = beam_search(inference_result, gt_len, final_k=20)
        res.append((1, masked, ground_truth, top_20_words))
    
        if len(top_20_words) != 20:
            c2 += 1

    found_in_top1 = False
    found_in_top20 = False
    
    if top_20_words:
        if top_20_words[0] == ground_truth:
            found_in_top1 = True
        if ground_truth in top_20_words:
            found_in_top20 = True

    if dialect in acc1 and gt_len in acc1[dialect]:
        acc1[dialect][gt_len].append(1 if found_in_top1 else 0)
        acc20[dialect][gt_len].append(1 if found_in_top20 else 0)
    
    if len(top_20_words) > 0:
        editd[dialect][gt_len].append(editdistance.eval(top_20_words[0], ground_truth) / gt_len)
    else:
        editd[dialect][gt_len].append(1.0)
    

for dialect in dialects:
    print(f"======== {dialect} ========")
    print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
    print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')
    
print(f"======== TOTAL ========")
acc1t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc1.items():
    for kk, v in vs.items():
        acc1t[kk].extend(v)

acc20t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc20.items():
    for kk, v in vs.items():
        acc20t[kk].extend(v)

cert = { x: [] for x in range(1, max_l+1)}
for k, vs in editd.items():
    for kk, v in vs.items():
        cert[kk].extend(v)
        
print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

print(c1, c2, c1+c2)

Device set to use cuda:0
100%|██████████| 95/95 [03:14<00:00,  2.05s/it]

======== atticionic ========
CER  : 56.97%
ACC1 : 29.20%
ACC20: 41.78%
======== doric ========
CER  : 61.14%
ACC1 : 20.00%
ACC20: 42.50%
======== northwest ========
CER  : 81.67%
ACC1 : 10.00%
ACC20: 60.00%
======== aeolic ========
CER  : 60.00%
ACC1 : 33.33%
ACC20: 33.33%
======== TOTAL ========
CER : 64.54%
ACC1 : 21.97%
ACC20 : 38.02%
5 4 9

### GreBerta Finetune

In [ ]:
model_name = "./models/greberta-archaic"
tokenizer = AutoTokenizer.from_pretrained(model_name)

roberta = True
strict_greek_pattern = re.compile(r"^[α-ω]+$")
fill_mask = pipeline("fill-mask", model=model_name, tokenizer=tokenizer, top_k=5000)

def beam_search(inference_result, target_length, final_k=20):
    if isinstance(inference_result[0], dict):
        inference_result = [inference_result]
    search_width = 1500
    beam = [(0.0, [])] 
    
    for mask_pos_candidates in inference_result:
        new_beam = []
        for current_score, current_tokens in beam:
            for candidate in mask_pos_candidates:
                token_str = candidate['token_str']
                if "-" in token_str:
                    continue
                score = candidate['score']
                
                new_score = current_score + math.log(score if score > 0 else 1e-10)
                new_tokens = current_tokens + [token_str]
                new_beam.append((new_score, new_tokens))

        new_beam.sort(key=lambda x: x[0], reverse=True)
        beam = new_beam[:search_width]
    
    valid_candidates = []
    for _, tokens in beam:
        if roberta:
            word = "".join(tokens).strip().replace(" ", "")
        else:
            word = "".join(tokens).replace("##", "")
        if len(word) == target_length:
            valid_candidates.append(word)

    valid_candidates = list(dict.fromkeys([
            strip_accents(x.lower())
            for x in valid_candidates 
            if len(x.replace(' ', '')) == target_length
            and strict_greek_pattern.match(strip_accents(x))
        ]))
    return valid_candidates[:final_k]


dialects = ['atticionic', 'doric', 'northwest', 'aeolic']
max_l = max(len(i['masked_gt']) for i in test_set) 

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc1 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
c1 = 0
c2 = 0
res = []
for inscription in tqdm(test_set):
    ground_truth = inscription['masked_gt']
    masked = inscription['masked_ag']
    dialect = inscription['dialect']
    gt_len = len(ground_truth)

    gt_tokens = tokenizer.tokenize(ground_truth)
    num_tokens = len(gt_tokens)

    multi_mask_str = " ".join(["[MASK]"] * num_tokens)
    masked_query = masked.replace("[MASK]", multi_mask_str)

    masked_query = masked.replace("[MASK]", "<mask>")
    inference_result = fill_mask(masked_query)

    top_20_words = []
    
    if num_tokens == 1: # If the word is made of just one token (simple case)
        clean_candidates = list(dict.fromkeys([
            strip_accents(x['token_str'].lower())
            for x in inference_result 
            if len(x['token_str'].replace(' ', '')) == len(ground_truth)
            and strict_greek_pattern.match(strip_accents(x['token_str']))
        ]))
        top_20_words = clean_candidates[:20]
        res.append((0, masked, ground_truth, top_20_words))
        if len(top_20_words) != 20:
            c1 += 1
    else: # If the word is made of multiple tokens (beam search)
        top_20_words = beam_search(inference_result, gt_len, final_k=20)
        res.append((1, masked, ground_truth, top_20_words))
    
        if len(top_20_words) != 20:
            c2 += 1

    found_in_top1 = False
    found_in_top20 = False
    
    if top_20_words:
        if top_20_words[0] == ground_truth:
            found_in_top1 = True
        if ground_truth in top_20_words:
            found_in_top20 = True

    if dialect in acc1 and gt_len in acc1[dialect]:
        acc1[dialect][gt_len].append(1 if found_in_top1 else 0)
        acc20[dialect][gt_len].append(1 if found_in_top20 else 0)
    
    if len(top_20_words) > 0:
        editd[dialect][gt_len].append(editdistance.eval(top_20_words[0], ground_truth) / gt_len)
    else:
        editd[dialect][gt_len].append(1.0)

for dialect in dialects:
    print(f"======== {dialect} ========")
    print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
    print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')
    
print(f"======== TOTAL ========")
acc1t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc1.items():
    for kk, v in vs.items():
        acc1t[kk].extend(v)

acc20t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc20.items():
    for kk, v in vs.items():
        acc20t[kk].extend(v)

cert = { x: [] for x in range(1, max_l+1)}
for k, vs in editd.items():
    for kk, v in vs.items():
        cert[kk].extend(v)
        
print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

print(c1, c2, c1+c2)

Device set to use cuda:0
100%|██████████| 95/95 [00:26<00:00,  3.60it/s]

======== atticionic ========
CER  : 83.02%
ACC1 : 3.85%
ACC20: 16.48%
======== doric ========
CER  : 75.39%
ACC1 : 17.50%
ACC20: 22.50%
======== northwest ========
CER  : 75.83%
ACC1 : 10.00%
ACC20: 40.00%
======== aeolic ========
CER  : 83.33%
ACC1 : 0.00%
ACC20: 0.00%
======== TOTAL ========
CER : 81.07%
ACC1 : 6.50%
ACC20 : 17.44%
2 12 14

In [ ]:
from transformers import pipeline, AutoTokenizer
from tqdm import tqdm
import math

model_name = "./models/greberta-archaic"
tokenizer = AutoTokenizer.from_pretrained(model_name)

fill_mask = pipeline("fill-mask", model=model_name, tokenizer=tokenizer, top_k=1000)

def beam_search(inference_result, target_length, final_k=20):
    search_width = 1500
    beam = [(0.0, [])] 
    for mask_pos_candidates in inference_result:
        new_beam = []
        for current_score, current_tokens in beam:
            for candidate in mask_pos_candidates:
                token_str = candidate['token_str']
                if "-" in token_str:
                    continue
                score = candidate['score']
                
                new_score = current_score + math.log(score if score > 0 else 1e-10)
                new_tokens = current_tokens + [token_str]
                new_beam.append((new_score, new_tokens))

        new_beam.sort(key=lambda x: x[0], reverse=True)
        beam = new_beam[:search_width]
    
    valid_candidates = []
    for _, tokens in beam:
        raw_word = "".join(tokens)
        word = raw_word.replace("Ġ", "").replace("##", "").strip()
        if len(word) == target_length:
            valid_candidates.append(word)
    
    clean_candidates = list(dict.fromkeys([
            strip_accents(x)
            for x in valid_candidates 
            if len(x) == target_length
        ]))
    return [x for x in clean_candidates if greek_pattern.match(x)][:final_k]


dialects = ['atticionic', 'doric', 'northwest', 'aeolic']
max_l = max(len(i['masked_gt']) for i in test_set) 

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc1 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
c1 = 0
c2 = 0
res = []
for inscription in tqdm(test_set):
    ground_truth = inscription['masked_gt']
    masked = inscription['masked_ag']
    dialect = inscription['dialect']
    gt_len = len(ground_truth)

    gt_tokens = tokenizer.tokenize(ground_truth)
    num_tokens = len(gt_tokens)

    multi_mask_str = " ".join(["<mask>"] * num_tokens)
    masked_query = masked.replace("[MASK]", multi_mask_str)

    inference_result = fill_mask(masked_query)

    top_20_words = []
    
    if num_tokens == 1: # If the word is made of just one token (simple case)

        clean_candidates = list(dict.fromkeys([
            strip_accents(x['token_str'])
            for x in inference_result 
            if len(x['token_str']) == len(ground_truth)
            and not x['token_str'].startswith("<extra_id_")
            and greek_pattern.match(x['token_str'])
        ]))
        
        top_20_words = clean_candidates[:20]
        res.append((0, masked, ground_truth, top_20_words))
        if len(top_20_words) != 20:
            c1 += 1
    else: # If the word is made of multiple tokens (beam search)
        top_20_words = beam_search(inference_result, gt_len, final_k=20)
        res.append((1, masked, ground_truth, top_20_words))
    
        if len(top_20_words) != 20:
            c2 += 1

    found_in_top1 = False
    found_in_top20 = False
    
    if top_20_words:
        if top_20_words[0] == ground_truth:
            found_in_top1 = True
        if ground_truth in top_20_words:
            found_in_top20 = True

    if dialect in acc1 and gt_len in acc1[dialect]:
        acc1[dialect][gt_len].append(1 if found_in_top1 else 0)
        acc20[dialect][gt_len].append(1 if found_in_top20 else 0)
    
    if len(top_20_words) > 0:
        editd[dialect][gt_len].append(editdistance.eval(top_20_words[0], ground_truth) / gt_len)
    else:
        editd[dialect][gt_len].append(1.0)
    

for dialect in dialects:
    print(f"======== {dialect} ========")
    print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
    print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')
    
print(f"======== TOTAL ========")
acc1t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc1.items():
    for kk, v in vs.items():
        acc1t[kk].extend(v)

acc20t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc20.items():
    for kk, v in vs.items():
        acc20t[kk].extend(v)

cert = { x: [] for x in range(1, max_l+1)}
for k, vs in editd.items():
    for kk, v in vs.items():
        cert[kk].extend(v)
        
print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

print(c1, c2, c1+c2)

Device set to use cuda:0
100%|██████████| 95/95 [12:21<00:00,  7.81s/it]

======== atticionic ========
CER  : 75.59%
ACC1 : 8.61%
ACC20: 25.67%
======== doric ========
CER  : 72.07%
ACC1 : 17.50%
ACC20: 22.50%
======== northwest ========
CER  : 77.50%
ACC1 : 10.00%
ACC20: 40.00%
======== aeolic ========
CER  : 80.83%
ACC1 : 0.00%
ACC20: 0.00%
======== TOTAL ========
CER : 76.60%
ACC1 : 9.33%
ACC20 : 23.02%
6 14 20

In [80]:
from transformers import pipeline, AutoTokenizer
from tqdm import tqdm
import math

model_name = "./models/greberta-archaic"
tokenizer = AutoTokenizer.from_pretrained(model_name)

fill_mask = pipeline("fill-mask", model=model_name, tokenizer=tokenizer, top_k=1000)

def beam_search(inference_result, target_length, final_k=20):
    search_width = 1000
    beam = [(0.0, [])] 
    for mask_pos_candidates in inference_result:
        new_beam = []
        for current_score, current_tokens in beam:
            for candidate in mask_pos_candidates:
                token_str = candidate['token_str']
                if "-" in token_str:
                    continue
                score = candidate['score']
                
                new_score = current_score + math.log(score if score > 0 else 1e-10)
                new_tokens = current_tokens + [token_str]
                new_beam.append((new_score, new_tokens))

        new_beam.sort(key=lambda x: x[0], reverse=True)
        beam = new_beam[:search_width]
    
    valid_candidates = []
    for _, tokens in beam:
        raw_word = "".join(tokens)
        word = raw_word.replace("Ġ", "").replace("##", "").strip()
        if len(word) == target_length:
            valid_candidates.append(word)
    
    clean_candidates = list(dict.fromkeys([
            strip_accents(x)
            for x in valid_candidates 
            if len(x) == target_length
        ]))
    return [x for x in clean_candidates if greek_pattern.match(x)][:final_k]


dialects = ['atticionic', 'doric', 'northwest', 'aeolic']
max_l = max(len(i['masked_gt']) for i in test_set) 

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc1 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
c1 = 0
c2 = 0
res = []
for inscription in tqdm(test_set):
    ground_truth = inscription['masked_gt']
    masked = inscription['masked_ag']
    dialect = inscription['dialect']
    gt_len = len(ground_truth)

    gt_tokens = tokenizer.tokenize(ground_truth)
    num_tokens = len(gt_tokens)

    multi_mask_str = "".join(["<mask>"] * num_tokens)
    masked_query = masked.replace("[MASK]", multi_mask_str)

    inference_result = fill_mask(masked_query)

    top_20_words = []
    
    if num_tokens == 1: # If the word is made of just one token (simple case)

        clean_candidates = list(dict.fromkeys([
            strip_accents(x['token_str'])
            for x in inference_result 
            if len(x['token_str']) == len(ground_truth)
            and not x['token_str'].startswith("<extra_id_")
            and greek_pattern.match(x['token_str'])
        ]))
        
        top_20_words = clean_candidates[:20]
        res.append((0, masked, ground_truth, top_20_words))
        if len(top_20_words) != 20:
            c1 += 1
    else: # If the word is made of multiple tokens (beam search)
        top_20_words = beam_search(inference_result, gt_len, final_k=20)
        res.append((1, masked, ground_truth, top_20_words))
    
        if len(top_20_words) != 20:
            c2 += 1

    found_in_top1 = False
    found_in_top20 = False
    
    if top_20_words:
        if top_20_words[0] == ground_truth:
            found_in_top1 = True
        if ground_truth in top_20_words:
            found_in_top20 = True

    if dialect in acc1 and gt_len in acc1[dialect]:
        acc1[dialect][gt_len].append(1 if found_in_top1 else 0)
        acc20[dialect][gt_len].append(1 if found_in_top20 else 0)
    
    if len(top_20_words) > 0:
        editd[dialect][gt_len].append(editdistance.eval(top_20_words[0], ground_truth) / gt_len)
    else:
        editd[dialect][gt_len].append(1.0)
    

for dialect in dialects:
    print(f"======== {dialect} ========")
    print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
    print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')
    
print(f"======== TOTAL ========")
acc1t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc1.items():
    for kk, v in vs.items():
        acc1t[kk].extend(v)

acc20t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc20.items():
    for kk, v in vs.items():
        acc20t[kk].extend(v)

cert = { x: [] for x in range(1, max_l+1)}
for k, vs in editd.items():
    for kk, v in vs.items():
        cert[kk].extend(v)
        
print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

print(c1, c2, c1+c2)

Device set to use cuda:0
100%|██████████| 95/95 [06:51<00:00,  4.34s/it]

======== atticionic ========
CER  : 75.59%
ACC1 : 8.61%
ACC20: 25.67%
======== doric ========
CER  : 72.07%
ACC1 : 17.50%
ACC20: 22.50%
======== northwest ========
CER  : 77.50%
ACC1 : 10.00%
ACC20: 40.00%
======== aeolic ========
CER  : 80.83%
ACC1 : 0.00%
ACC20: 0.00%
======== TOTAL ========
CER : 76.60%
ACC1 : 9.33%
ACC20 : 23.02%
6 16 22

In [82]:
from transformers import pipeline, AutoTokenizer
from tqdm import tqdm
import math

model_name = "./models/philberta-archaic"
tokenizer = AutoTokenizer.from_pretrained(model_name)

fill_mask = pipeline("fill-mask", model=model_name, tokenizer=tokenizer, top_k=1000)

def beam_search(inference_result, target_length, final_k=20):
    search_width = 1000
    beam = [(0.0, [])] 
    for mask_pos_candidates in inference_result:
        new_beam = []
        for current_score, current_tokens in beam:
            for candidate in mask_pos_candidates:
                token_str = candidate['token_str']
                if "-" in token_str:
                    continue
                score = candidate['score']
                
                new_score = current_score + math.log(score if score > 0 else 1e-10)
                new_tokens = current_tokens + [token_str]
                new_beam.append((new_score, new_tokens))

        new_beam.sort(key=lambda x: x[0], reverse=True)
        beam = new_beam[:search_width]
    
    valid_candidates = []
    for _, tokens in beam:
        raw_word = "".join(tokens)
        word = raw_word.replace("Ġ", "").replace("##", "").strip()
        if len(word) == target_length:
            valid_candidates.append(word)
    
    clean_candidates = list(dict.fromkeys([
            strip_accents(x)
            for x in valid_candidates 
            if len(x) == target_length
        ]))
    return [x for x in clean_candidates if greek_pattern.match(x)][:final_k]


dialects = ['atticionic', 'doric', 'northwest', 'aeolic']
max_l = max(len(i['masked_gt']) for i in test_set) 

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc1 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = {d: {x: [] for x in range(1, max_l+1)} for d in dialects}
c1 = 0
c2 = 0
res = []
for inscription in tqdm(test_set):
    ground_truth = inscription['masked_gt']
    masked = inscription['masked_ag']
    dialect = inscription['dialect']
    gt_len = len(ground_truth)

    gt_tokens = tokenizer.tokenize(ground_truth)
    num_tokens = len(gt_tokens)

    multi_mask_str = "".join(["<mask>"] * num_tokens)
    masked_query = masked.replace("[MASK]", multi_mask_str)

    inference_result = fill_mask(masked_query)

    top_20_words = []
    
    if num_tokens == 1: # If the word is made of just one token (simple case)

        clean_candidates = list(dict.fromkeys([
            strip_accents(x['token_str'])
            for x in inference_result 
            if len(x['token_str']) == len(ground_truth)
            and not x['token_str'].startswith("<extra_id_")
            and greek_pattern.match(x['token_str'])
        ]))
        
        top_20_words = clean_candidates[:20]
        res.append((0, masked, ground_truth, top_20_words))
        if len(top_20_words) != 20:
            c1 += 1
    else: # If the word is made of multiple tokens (beam search)
        top_20_words = beam_search(inference_result, gt_len, final_k=20)
        res.append((1, masked, ground_truth, top_20_words))
    
        if len(top_20_words) != 20:
            c2 += 1

    found_in_top1 = False
    found_in_top20 = False
    
    if top_20_words:
        if top_20_words[0] == ground_truth:
            found_in_top1 = True
        if ground_truth in top_20_words:
            found_in_top20 = True

    if dialect in acc1 and gt_len in acc1[dialect]:
        acc1[dialect][gt_len].append(1 if found_in_top1 else 0)
        acc20[dialect][gt_len].append(1 if found_in_top20 else 0)
    
    if len(top_20_words) > 0:
        editd[dialect][gt_len].append(editdistance.eval(top_20_words[0], ground_truth) / gt_len)
    else:
        editd[dialect][gt_len].append(1.0)
    

for dialect in dialects:
    print(f"======== {dialect} ========")
    print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
    print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')
    
print(f"======== TOTAL ========")
acc1t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc1.items():
    for kk, v in vs.items():
        acc1t[kk].extend(v)

acc20t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc20.items():
    for kk, v in vs.items():
        acc20t[kk].extend(v)

cert = { x: [] for x in range(1, max_l+1)}
for k, vs in editd.items():
    for kk, v in vs.items():
        cert[kk].extend(v)
        
print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

print(c1, c2, c1+c2)

Device set to use cuda:0
100%|██████████| 95/95 [07:36<00:00,  4.80s/it]

======== atticionic ========
CER  : 68.07%
ACC1 : 18.60%
ACC20: 28.67%
======== doric ========
CER  : 67.63%
ACC1 : 17.50%
ACC20: 27.50%
======== northwest ========
CER  : 65.00%
ACC1 : 20.00%
ACC20: 60.00%
======== aeolic ========
CER  : 60.00%
ACC1 : 0.00%
ACC20: 0.00%
======== TOTAL ========
CER : 70.10%
ACC1 : 15.13%
ACC20 : 25.79%
5 17 22

### Greta Finetune

In [83]:
import torch
import numpy as np
import editdistance
from tqdm import tqdm
from transformers import T5Tokenizer, T5ForConditionalGeneration
import re

greek_pattern = re.compile(r"^[\u0370-\u03FF\u1F00-\u1FFF]+$")

model_name = "./models/greta-archaic"
device = "cuda" if torch.cuda.is_available() else "cpu"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name).to(device)
model.eval()

def t5_fill_mask(masked_text, top_k=3500):
    t5_input = masked_text.replace("[MASK]", "<extra_id_0>")
    
    inputs = tokenizer(t5_input, return_tensors="pt").to(device)
    
    # Prepare the decoder input. 
    # We want T5 to start generating from the first sentinel.
    # The standard start sequence for filling <extra_id_0> is: <pad> <extra_id_0>
    decoder_input_ids = tokenizer("<pad> <extra_id_0>", return_tensors="pt", add_special_tokens=False).input_ids.to(device)

    with torch.no_grad():
        outputs = model(input_ids=inputs.input_ids, decoder_input_ids=decoder_input_ids)


    next_token_logits = outputs.logits[0, -1, :]
    probs = torch.softmax(next_token_logits, dim=-1)
    top_k_probs, top_k_ids = torch.topk(probs, top_k)
    
    results = []
    for score, token_id in zip(top_k_probs, top_k_ids):
        token_str = tokenizer.decode(token_id).replace(" ", "").strip()
        
        # Skip empty strings or special tokens if necessary
        if not token_str: continue
        
        results.append({"token_str": token_str, "score": score.item()})
        
    return results


max_l = 20 
dialects = set(inscription['dialect'] for inscription in test_set)

ctop1s = []
ctop20s = []

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc1 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}

pbar = tqdm(test_set)

res = []
for inscription in pbar:
    ground_truth = inscription['masked_gt']
    masked = inscription['masked_ag']
    dialect = inscription['dialect']
    

    inference_result = t5_fill_mask(masked, top_k=3500)

    # constr = [ strip_accents(x['token_str']) for x in inference_result if len(x['token_str']) == len(ground_truth)][:20]
    constr = list(dict.fromkeys([
    strip_accents(x['token_str']) 
    for x in inference_result 
    if len(x['token_str']) == len(ground_truth)
    and not x['token_str'].startswith("<extra_id_")
    and greek_pattern.match(strip_accents(x['token_str']))
    ]))[:20]

    ctop1 = 0
    ctop20 = 0
    
    if constr and ground_truth == constr[0]:
        ctop1 = 1
        ctop20 = 1
    
    elif ground_truth in [x for x in constr]:
        ctop20 = 1

    ctop1s.append(ctop1)
    ctop20s.append(ctop20)
    
    gt_len = len(ground_truth)
    if gt_len in acc1[dialect]:
        acc1[dialect][gt_len].append(ctop1)
        acc20[dialect][gt_len].append(ctop20)

        if constr:
            score = editdistance.eval(constr[0], ground_truth) / len(ground_truth)
            editd[dialect][gt_len].append(score)
        else:
            editd[dialect][gt_len].append(1.0)
    res.append((masked, ground_truth, constr))

for dialect in dialects:
    print(f"======== {dialect} ========")
    cer_vals = [np.mean(v) for v in editd[dialect].values() if v]
    acc1_vals = [np.mean(v) for v in acc1[dialect].values() if v]
    acc20_vals = [np.mean(v) for v in acc20[dialect].values() if v]
    
    print(f'CER  : {np.mean(cer_vals)*100:.2f}%' if cer_vals else 'CER  : N/A')
    print(f'ACC1 : {np.mean(acc1_vals)*100:.2f}%' if acc1_vals else 'ACC1 : N/A')
    print(f'ACC20: {np.mean(acc20_vals)*100:.2f}%' if acc20_vals else 'ACC20: N/A')

print(f"======== TOTAL ========")
cert = [val for sublist in editd.values() for v in sublist.values() for val in v]
acc1t = [val for sublist in acc1.values() for v in sublist.values() for val in v]
acc20t = [val for sublist in acc20.values() for v in sublist.values() for val in v]

print(f'CER : {np.mean(cert)*100:.2f}%' if cert else 'CER : N/A')
print(f'ACC1 : {np.mean(acc1t)*100:.2f}%' if acc1t else 'ACC1 : N/A')
print(f'ACC20 : {np.mean(acc20t)*100:.2f}%' if acc20t else 'ACC20 : N/A')

100%|██████████| 95/95 [00:16<00:00,  5.85it/s]

======== atticionic ========
CER  : 85.91%
ACC1 : 1.92%
ACC20: 11.54%
======== aeolic ========
CER  : 95.83%
ACC1 : 0.00%
ACC20: 0.00%
======== doric ========
CER  : 91.64%
ACC1 : 0.00%
ACC20: 10.00%
======== northwest ========
CER  : 92.50%
ACC1 : 0.00%
ACC20: 50.00%
======== TOTAL ========
CER : 87.89%
ACC1 : 1.05%
ACC20 : 12.63%

### Philta

In [84]:
import torch
import numpy as np
import editdistance
from tqdm import tqdm
from transformers import T5Tokenizer, T5ForConditionalGeneration
import re

greek_pattern = re.compile(r"^[\u0370-\u03FF\u1F00-\u1FFF]+$")

model_name = "./models/philta-archaic"
device = "cuda" if torch.cuda.is_available() else "cpu"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name).to(device)
model.eval()

def t5_fill_mask(masked_text, top_k=3500):
    t5_input = masked_text.replace("[MASK]", "<extra_id_0>")
    
    inputs = tokenizer(t5_input, return_tensors="pt").to(device)
    
    # Prepare the decoder input. 
    # We want T5 to start generating from the first sentinel.
    # The standard start sequence for filling <extra_id_0> is: <pad> <extra_id_0>
    decoder_input_ids = tokenizer("<pad> <extra_id_0>", return_tensors="pt", add_special_tokens=False).input_ids.to(device)

    with torch.no_grad():
        outputs = model(input_ids=inputs.input_ids, decoder_input_ids=decoder_input_ids)


    next_token_logits = outputs.logits[0, -1, :]
    probs = torch.softmax(next_token_logits, dim=-1)
    top_k_probs, top_k_ids = torch.topk(probs, top_k)
    
    results = []
    for score, token_id in zip(top_k_probs, top_k_ids):
        token_str = tokenizer.decode(token_id).replace(" ", "").strip()
        
        # Skip empty strings or special tokens if necessary
        if not token_str: continue
        
        results.append({"token_str": token_str, "score": score.item()})
        
    return results


max_l = 20 
dialects = set(inscription['dialect'] for inscription in test_set)

ctop1s = []
ctop20s = []

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc1 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}

pbar = tqdm(test_set)

res = []
for inscription in pbar:
    ground_truth = inscription['masked_gt']
    masked = inscription['masked_ag']
    dialect = inscription['dialect']
    

    inference_result = t5_fill_mask(masked, top_k=3500)

    # constr = [ strip_accents(x['token_str']) for x in inference_result if len(x['token_str']) == len(ground_truth)][:20]
    constr = list(dict.fromkeys([
    strip_accents(x['token_str']) 
    for x in inference_result 
    if len(x['token_str']) == len(ground_truth)
    and not x['token_str'].startswith("<extra_id_")
    and greek_pattern.match(strip_accents(x['token_str']))
    ]))[:20]

    ctop1 = 0
    ctop20 = 0
    
    if constr and ground_truth == constr[0]:
        ctop1 = 1
        ctop20 = 1
    
    elif ground_truth in [x for x in constr]:
        ctop20 = 1

    ctop1s.append(ctop1)
    ctop20s.append(ctop20)
    
    gt_len = len(ground_truth)
    if gt_len in acc1[dialect]:
        acc1[dialect][gt_len].append(ctop1)
        acc20[dialect][gt_len].append(ctop20)

        if constr:
            score = editdistance.eval(constr[0], ground_truth) / len(ground_truth)
            editd[dialect][gt_len].append(score)
        else:
            editd[dialect][gt_len].append(1.0)
    res.append((masked, ground_truth, constr))

for dialect in dialects:
    print(f"======== {dialect} ========")
    cer_vals = [np.mean(v) for v in editd[dialect].values() if v]
    acc1_vals = [np.mean(v) for v in acc1[dialect].values() if v]
    acc20_vals = [np.mean(v) for v in acc20[dialect].values() if v]
    
    print(f'CER  : {np.mean(cer_vals)*100:.2f}%' if cer_vals else 'CER  : N/A')
    print(f'ACC1 : {np.mean(acc1_vals)*100:.2f}%' if acc1_vals else 'ACC1 : N/A')
    print(f'ACC20: {np.mean(acc20_vals)*100:.2f}%' if acc20_vals else 'ACC20: N/A')

print(f"======== TOTAL ========")
cert = [val for sublist in editd.values() for v in sublist.values() for val in v]
acc1t = [val for sublist in acc1.values() for v in sublist.values() for val in v]
acc20t = [val for sublist in acc20.values() for v in sublist.values() for val in v]

print(f'CER : {np.mean(cert)*100:.2f}%' if cert else 'CER : N/A')
print(f'ACC1 : {np.mean(acc1t)*100:.2f}%' if acc1t else 'ACC1 : N/A')
print(f'ACC20 : {np.mean(acc20t)*100:.2f}%' if acc20t else 'ACC20 : N/A')

100%|██████████| 95/95 [00:17<00:00,  5.53it/s]

======== atticionic ========
CER  : 80.67%
ACC1 : 7.69%
ACC20: 18.59%
======== aeolic ========
CER  : 95.83%
ACC1 : 0.00%
ACC20: 0.00%
======== doric ========
CER  : 86.45%
ACC1 : 0.00%
ACC20: 10.00%
======== northwest ========
CER  : 85.00%
ACC1 : 10.00%
ACC20: 60.00%
======== TOTAL ========
CER : 82.48%
ACC1 : 5.26%
ACC20 : 16.84%

#### Additional test case (Epigr_3)

In [31]:
import json
from transformers import pipeline, AutoTokenizer, LlamaForCausalLM, AutoModelForCausalLM
from accelerate import init_empty_weights, load_checkpoint_and_dispatch
import torch
import warnings
warnings.filterwarnings("ignore", message=".*copying from a non-meta parameter in the checkpoint*")
model_id = "Ericu950/Epigr_3_Llama-3.1-8B-Instruct_text"

with init_empty_weights():
    model = LlamaForCausalLM.from_pretrained(model_id)

model = LlamaForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
    torch_dtype=torch.float16, # Recommended for Llama to save memory
    offload_folder="offload"
)

tokenizer = AutoTokenizer.from_pretrained(model_id)

generation_pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    device_map="auto",
)

# 7 + 1 space
inscription_edition = "θιοι εαδε λυκτιοισι αλλοπολιαταν οστις κα δεκσεται ερρεν αι μη οσωυτος τε καρτει [7 missing letters] ιτανιονς αι δε καρτησαι η κοσμιων η αποκοσμος υπερ ωλας αδας εκατον λεβητας τεισει εκαστω οσος κα δεκσεται τουτος δε οι εσζικαιωτηρες επ ο τε κα παυσεται αι κα μη ανιωνται παρ τωι επιορωι ομιονται αποδομεν"
system_prompt = "Fill in the missing letters in this inscription!"
input_messages = [
    {"role": "system", "content": system_prompt},
    {"role": "user", "content": inscription_edition},
]
terminators = [
    tokenizer.eos_token_id,
    tokenizer.convert_tokens_to_ids("<|eot_id|>")
]
outputs = generation_pipeline(
    input_messages,
    max_new_tokens=10,
    num_beams=30, # Set this as high as your memory will allow!
    num_return_sequences=20,
    early_stopping=True,
)
beam_contents = []
for output in outputs:
    generated_text = output.get('generated_text', [])
    for item in generated_text:
        if item.get('role') == 'assistant':
            beam_contents.append(item.get('content'))
real_response = "και τονς"
print(f"The masked sequence: {real_response}")
for i, content in enumerate(beam_contents, start=1):
    print(f"Suggestion {i}: {content}")

Loading checkpoint shards: 100%|██████████| 4/4 [00:03<00:00,  1.07it/s]
Loading checkpoint shards: 100%|██████████| 4/4 [00:01<00:00,  2.08it/s]
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Device set to use cuda:0
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

The masked sequence: και τονς
Suggestion 1: εσζικαι
Suggestion 2: επιορωι
Suggestion 3: επιορων
Suggestion 4: κοσμιων
Suggestion 5: παρ τοις
Suggestion 6: παρ τανς
Suggestion 7: επιορου
Suggestion 8: επ ερρεν
Suggestion 9: εσζικαν
Suggestion 10: επ εσζικ
Suggestion 11: επιορω ε
Suggestion 12: εσζικατ
Suggestion 13: εσζικεν
Suggestion 14: εσζικαω
Suggestion 15: οστις κα
Suggestion 16: πεντε ετ
Suggestion 17: μη εσζεν
Suggestion 18: επιορως
Suggestion 19: επιορωσ
Suggestion 20: επ εσζεν

In [33]:
for i, content in enumerate(beam_contents, start=1):
    print(f"Suggestion {i}: {len(content), ' ' in content}")

Suggestion 1: (7, False)
Suggestion 2: (7, False)
Suggestion 3: (7, False)
Suggestion 4: (7, False)
Suggestion 5: (8, True)
Suggestion 6: (8, True)
Suggestion 7: (7, False)
Suggestion 8: (8, True)
Suggestion 9: (7, False)
Suggestion 10: (8, True)
Suggestion 11: (8, True)
Suggestion 12: (7, False)
Suggestion 13: (7, False)
Suggestion 14: (7, False)
Suggestion 15: (8, True)
Suggestion 16: (8, True)
Suggestion 17: (8, True)
Suggestion 18: (7, False)
Suggestion 19: (7, False)
Suggestion 20: (8, True)

1. Mask only words

In [ ]:
import torch
import numpy as np
import random

seed = 42
random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed_all(seed)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

ctop1s = []
ctop20s = []

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}

acc1 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}

res = []
pbar = tqdm(test_set)
for inscription in pbar:
    ground_truth = inscription['masked_gt']
    
    masked = inscription['masked_ag'].replace('[MASK]', f"[{len(ground_truth)} missing letters]" )

    dialect = inscription['dialect']
    
    system_prompt = "Fill in the missing letters in this inscription!"
    input_messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": masked},
    ]
    terminators = [
        tokenizer.eos_token_id,
        tokenizer.convert_tokens_to_ids("<|eot_id|>")
    ]
    outputs = generation_pipeline(
        input_messages,
        max_new_tokens=10,
        num_beams=300, # Set this as high as your memory will allow!
        num_return_sequences=300,
        early_stopping=True,
        do_sample=False
    )
    constr = []
    for output in outputs:
        generated_text = output.get('generated_text', [])
        for item in generated_text:
            if item.get('role') == 'assistant':
                if len(constr) < 20 and len(item.get('content')) == len(ground_truth):
                    constr.append(item.get('content'))
    
    res.append(len(constr))


    ctop1 = 0
    ctop20 = 0
    if ground_truth in [ x for x in constr[:1] ]:
        ctop1 = 1
        ctop20 = 1
    if ground_truth in [ x for x in constr ]:
        ctop20 = 1

    ctop1s.append(ctop1)
    ctop20s.append(ctop20)
    acc1[dialect][len(ground_truth)].append(ctop1)
    acc20[dialect][len(ground_truth)].append(ctop20)

    if constr != []:
        editd[dialect][len(ground_truth)].append(editdistance.eval(constr[0], ground_truth) / len(ground_truth))
    else:
        editd[dialect][len(ground_truth)].append(1.0)

for dialect in dialects:
    print(f"======== {dialect} ========")
    print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
    print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')

print(f"======== TOTAL ========")
cert = { x: [] for x in range(1, max_l+1)}
for k, vs in editd.items():
    for kk, v in vs.items():
        cert[kk].extend(v)
acc1t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc1.items():
    for kk, v in vs.items():
        acc1t[kk].extend(v)

acc20t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc20.items():
    for kk, v in vs.items():
        acc20t[kk].extend(v)
print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')
print(len([1 for x in res if x<20]))

  0%|          | 0/95 [00:00<?, ?it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 1/95 [00:03<05:06,  3.26s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 2/95 [00:05<03:57,  2.55s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 3/95 [00:08<04:03,  2.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▍         | 4/95 [00:11<04:22,  2.89s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  5%|▌         | 5/95 [00:13<03:58,  2.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  6%|▋         | 6/95 [00:15<03:48,  2.57s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  7%|▋         | 7/95 [00:19<04:01,  2.75s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  8%|▊         | 8/95 [00:21<03:43,  2.57s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  9%|▉         | 9/95 [00:23<03:36,  2.52s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 11%|█         | 10/95 [00:25<03:24,  2.41s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 12%|█▏        | 11/95 [00:28<03:31,  2.52s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 13%|█▎        | 12/95 [00:31<03:44,  2.70s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 14%|█▎        | 13/95 [00:34<03:33,  2.60s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 15%|█▍        | 14/95 [00:36<03:24,  2.53s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 16%|█▌        | 15/95 [00:38<03:17,  2.47s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 17%|█▋        | 16/95 [00:42<03:48,  2.90s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 18%|█▊        | 17/95 [00:44<03:29,  2.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 19%|█▉        | 18/95 [00:47<03:16,  2.55s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 20%|██        | 19/95 [00:50<03:36,  2.85s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 21%|██        | 20/95 [00:54<03:46,  3.02s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 22%|██▏       | 21/95 [00:58<04:15,  3.46s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 23%|██▎       | 22/95 [01:01<04:00,  3.30s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 24%|██▍       | 23/95 [01:03<03:34,  2.98s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 25%|██▌       | 24/95 [01:05<03:16,  2.76s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 26%|██▋       | 25/95 [01:07<02:55,  2.51s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 27%|██▋       | 26/95 [01:10<03:04,  2.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 28%|██▊       | 27/95 [01:13<03:01,  2.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 29%|██▉       | 28/95 [01:16<02:59,  2.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 31%|███       | 29/95 [01:18<02:46,  2.52s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 32%|███▏      | 30/95 [01:21<03:01,  2.79s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 33%|███▎      | 31/95 [01:24<02:49,  2.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 34%|███▎      | 32/95 [01:26<02:39,  2.54s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 35%|███▍      | 33/95 [01:28<02:35,  2.50s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 36%|███▌      | 34/95 [01:31<02:29,  2.46s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 37%|███▋      | 35/95 [01:33<02:21,  2.36s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 38%|███▊      | 36/95 [01:35<02:22,  2.42s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 39%|███▉      | 37/95 [01:40<02:49,  2.92s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 40%|████      | 38/95 [01:41<02:30,  2.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 41%|████      | 39/95 [01:43<02:16,  2.43s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 42%|████▏     | 40/95 [01:50<03:14,  3.54s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 43%|████▎     | 41/95 [01:52<02:50,  3.15s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 44%|████▍     | 42/95 [01:55<02:40,  3.02s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 45%|████▌     | 43/95 [01:58<02:43,  3.14s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 46%|████▋     | 44/95 [02:00<02:27,  2.89s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 47%|████▋     | 45/95 [02:03<02:17,  2.74s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 48%|████▊     | 46/95 [02:05<02:13,  2.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 49%|████▉     | 47/95 [02:09<02:19,  2.90s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 51%|█████     | 48/95 [02:11<02:09,  2.76s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 52%|█████▏    | 49/95 [02:14<02:08,  2.80s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 53%|█████▎    | 50/95 [02:16<01:53,  2.53s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 54%|█████▎    | 51/95 [02:18<01:47,  2.44s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 55%|█████▍    | 52/95 [02:21<01:53,  2.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 56%|█████▌    | 53/95 [02:26<02:19,  3.33s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 57%|█████▋    | 54/95 [02:29<02:07,  3.11s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 58%|█████▊    | 55/95 [02:31<01:54,  2.87s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 59%|█████▉    | 56/95 [02:35<02:07,  3.28s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 60%|██████    | 57/95 [02:38<01:53,  2.98s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 61%|██████    | 58/95 [02:40<01:49,  2.95s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 62%|██████▏   | 59/95 [02:43<01:37,  2.70s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 63%|██████▎   | 60/95 [02:45<01:27,  2.51s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 64%|██████▍   | 61/95 [02:50<01:51,  3.28s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 65%|██████▌   | 62/95 [02:54<01:55,  3.50s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 66%|██████▋   | 63/95 [02:58<01:59,  3.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 67%|██████▋   | 64/95 [03:01<01:51,  3.59s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 68%|██████▊   | 65/95 [03:03<01:33,  3.13s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 69%|██████▉   | 66/95 [03:06<01:25,  2.95s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 71%|███████   | 67/95 [03:08<01:19,  2.82s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 72%|███████▏  | 68/95 [03:11<01:10,  2.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 73%|███████▎  | 69/95 [03:21<02:05,  4.83s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 74%|███████▎  | 70/95 [03:23<01:43,  4.14s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 75%|███████▍  | 71/95 [03:29<01:49,  4.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 76%|███████▌  | 72/95 [03:32<01:33,  4.08s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 77%|███████▋  | 73/95 [03:34<01:20,  3.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 78%|███████▊  | 74/95 [03:37<01:09,  3.30s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 79%|███████▉  | 75/95 [03:40<01:04,  3.21s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 80%|████████  | 76/95 [03:42<00:56,  2.97s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 81%|████████  | 77/95 [03:44<00:49,  2.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 82%|████████▏ | 78/95 [03:47<00:47,  2.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 83%|████████▎ | 79/95 [03:54<01:03,  3.99s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 84%|████████▍ | 80/95 [03:56<00:52,  3.50s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 85%|████████▌ | 81/95 [03:59<00:44,  3.17s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 86%|████████▋ | 82/95 [04:01<00:37,  2.88s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 87%|████████▋ | 83/95 [04:04<00:33,  2.79s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 88%|████████▊ | 84/95 [04:06<00:29,  2.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 89%|████████▉ | 85/95 [04:10<00:30,  3.04s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 91%|█████████ | 86/95 [04:13<00:26,  2.91s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 92%|█████████▏| 87/95 [04:15<00:23,  2.90s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 93%|█████████▎| 88/95 [04:17<00:18,  2.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 94%|█████████▎| 89/95 [04:20<00:16,  2.75s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 95%|█████████▍| 90/95 [04:23<00:13,  2.75s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 96%|█████████▌| 91/95 [04:26<00:10,  2.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 97%|█████████▋| 92/95 [04:30<00:09,  3.04s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 98%|█████████▊| 93/95 [04:32<00:05,  2.85s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 99%|█████████▉| 94/95 [04:34<00:02,  2.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
100%|██████████| 95/95 [04:38<00:00,  2.93s/it]

======== atticionic ========
CER  : 34.84%
ACC1 : 56.31%
ACC20: 67.94%
======== doric ========
CER  : 63.98%
ACC1 : 27.50%
ACC20: 64.17%
======== northwest ========
CER  : 60.83%
ACC1 : 30.00%
ACC20: 50.00%
======== aeolic ========
CER  : 60.00%
ACC1 : 33.33%
ACC20: 33.33%
======== TOTAL ========
CER : 46.80%
ACC1 : 43.23%
ACC20 : 58.44%
9

# Investingating contamination
Has the model aready seen the data. Knowing that Epigr_3 was a fintune of the model that has only seen papyri. Is the latter much worse?

======== atticionic ========
CER  : 39.08%
ACC1 : 44.69%
ACC20: 58.69%
======== doric ========
CER  : 63.95%
ACC1 : 27.50%
ACC20: 47.50%
======== northwest ========
CER  : 59.17%
ACC1 : 30.00%
ACC20: 50.00%
======== aeolic ========
CER  : 60.00%
ACC1 : 33.33%
ACC20: 33.33%
======== TOTAL ========
CER : 48.77%
ACC1 : 37.80%
ACC20 : 52.59%

In [3]:
import json
from transformers import pipeline, AutoTokenizer, LlamaForCausalLM, AutoModelForCausalLM
from accelerate import init_empty_weights, load_checkpoint_and_dispatch
import torch
import warnings
warnings.filterwarnings("ignore", message=".*copying from a non-meta parameter in the checkpoint*")
model_id = "Ericu950/Papy_2_Llama-3.1-8B-Instruct_text"

with init_empty_weights():
    model = LlamaForCausalLM.from_pretrained(model_id)

model = LlamaForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
    torch_dtype=torch.float16, # Recommended for Llama to save memory
    offload_folder="offload"
)

tokenizer = AutoTokenizer.from_pretrained(model_id)

generation_pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    device_map="auto",
)

Fetching 4 files: 100%|██████████| 4/4 [02:01<00:00, 30.28s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:03<00:00,  1.21it/s]
`torch_dtype` is deprecated! Use `dtype` instead!
Loading checkpoint shards: 100%|██████████| 4/4 [00:04<00:00,  1.07s/it]
Device set to use cuda:0

In [4]:
ctop1s = []
ctop20s = []

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc1 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}

pbar = tqdm(test_set)
for inscription in pbar:
    ground_truth = inscription['masked_gt']
    
    masked = inscription['masked_ag'].replace('[MASK]', f"[{len(ground_truth)} missing letters]" )

    dialect = inscription['dialect']
    
    system_prompt = "Fill in the missing letters in this inscription!"
    input_messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": masked},
    ]
    terminators = [
        tokenizer.eos_token_id,
        tokenizer.convert_tokens_to_ids("<|eot_id|>")
    ]
    outputs = generation_pipeline(
        input_messages,
        max_new_tokens=10,
        num_beams=30, # Set this as high as your memory will allow!
        num_return_sequences=20,
        early_stopping=True,
    )
    constr = []
    for output in outputs:
        generated_text = output.get('generated_text', [])
        for item in generated_text:
            if item.get('role') == 'assistant':
                constr.append(item.get('content'))


    ctop1 = 0
    ctop20 = 0
    if ground_truth in [ x for x in constr[:1] ]:
        ctop1 = 1
        ctop20 = 1
    if ground_truth in [ x for x in constr ]:
        ctop20 = 1

    ctop1s.append(ctop1)
    ctop20s.append(ctop20)
    acc1[dialect][len(ground_truth)].append(ctop1)
    acc20[dialect][len(ground_truth)].append(ctop20)

    if constr != []:
        editd[dialect][len(ground_truth)].append(editdistance.eval(constr[0], ground_truth) / len(ground_truth))
    else:
        editd[dialect][len(ground_truth)].append(1.0)

for dialect in dialects:
    print(f"======== {dialect} ========")
    print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
    print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')

print(f"======== TOTAL ========")
cert = { x: [] for x in range(1, max_l+1)}
for k, vs in editd.items():
    for kk, v in vs.items():
        cert[kk].extend(v)
acc1t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc1.items():
    for kk, v in vs.items():
        acc1t[kk].extend(v)

acc20t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc20.items():
    for kk, v in vs.items():
        acc20t[kk].extend(v)
print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

  0%|          | 0/95 [00:00<?, ?it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 1/95 [00:02<03:37,  2.32s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 2/95 [00:02<01:43,  1.11s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 3/95 [00:03<01:13,  1.26it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▍         | 4/95 [00:03<00:57,  1.59it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  5%|▌         | 5/95 [00:03<00:48,  1.86it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  6%|▋         | 6/95 [00:04<00:43,  2.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  7%|▋         | 7/95 [00:04<00:40,  2.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  8%|▊         | 8/95 [00:04<00:36,  2.37it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  9%|▉         | 9/95 [00:05<00:36,  2.37it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 11%|█         | 10/95 [00:05<00:34,  2.50it/s]You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 12%|█▏        | 11/95 [00:06<00:36,  2.29it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 13%|█▎        | 12/95 [00:06<00:38,  2.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 14%|█▎        | 13/95 [00:07<00:37,  2.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 15%|█▍        | 14/95 [00:07<00:34,  2.35it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 16%|█▌        | 15/95 [00:07<00:29,  2.71it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 17%|█▋        | 16/95 [00:08<00:30,  2.58it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 18%|█▊        | 17/95 [00:08<00:26,  2.92it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 19%|█▉        | 18/95 [00:08<00:26,  2.91it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 20%|██        | 19/95 [00:09<00:27,  2.78it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 21%|██        | 20/95 [00:09<00:29,  2.53it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 22%|██▏       | 21/95 [00:10<00:35,  2.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 23%|██▎       | 22/95 [00:10<00:33,  2.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 24%|██▍       | 23/95 [00:11<00:34,  2.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 25%|██▌       | 24/95 [00:11<00:30,  2.29it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 26%|██▋       | 25/95 [00:11<00:28,  2.46it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 27%|██▋       | 26/95 [00:12<00:26,  2.56it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 28%|██▊       | 27/95 [00:12<00:25,  2.66it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 29%|██▉       | 28/95 [00:13<00:25,  2.59it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 31%|███       | 29/95 [00:13<00:25,  2.59it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 32%|███▏      | 30/95 [00:13<00:28,  2.32it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 33%|███▎      | 31/95 [00:14<00:24,  2.58it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 34%|███▎      | 32/95 [00:14<00:24,  2.60it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 35%|███▍      | 33/95 [00:15<00:24,  2.53it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 36%|███▌      | 34/95 [00:15<00:21,  2.78it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 37%|███▋      | 35/95 [00:15<00:22,  2.72it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 38%|███▊      | 36/95 [00:16<00:22,  2.65it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 39%|███▉      | 37/95 [00:16<00:25,  2.30it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 40%|████      | 38/95 [00:16<00:22,  2.52it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 41%|████      | 39/95 [00:17<00:19,  2.86it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 42%|████▏     | 40/95 [00:18<00:28,  1.95it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 43%|████▎     | 41/95 [00:18<00:25,  2.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 44%|████▍     | 42/95 [00:18<00:23,  2.25it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 45%|████▌     | 43/95 [00:19<00:23,  2.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 46%|████▋     | 44/95 [00:19<00:20,  2.48it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 47%|████▋     | 45/95 [00:20<00:19,  2.51it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 48%|████▊     | 46/95 [00:20<00:19,  2.56it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 49%|████▉     | 47/95 [00:20<00:20,  2.35it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 51%|█████     | 48/95 [00:21<00:19,  2.36it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 52%|█████▏    | 49/95 [00:21<00:20,  2.30it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 53%|█████▎    | 50/95 [00:22<00:18,  2.40it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 54%|█████▎    | 51/95 [00:22<00:17,  2.47it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 55%|█████▍    | 52/95 [00:22<00:16,  2.56it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 56%|█████▌    | 53/95 [00:23<00:19,  2.20it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 57%|█████▋    | 54/95 [00:23<00:17,  2.40it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 58%|█████▊    | 55/95 [00:24<00:16,  2.46it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 59%|█████▉    | 56/95 [00:24<00:16,  2.33it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 60%|██████    | 57/95 [00:25<00:16,  2.29it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 61%|██████    | 58/95 [00:25<00:14,  2.49it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 62%|██████▏   | 59/95 [00:25<00:13,  2.76it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 63%|██████▎   | 60/95 [00:25<00:11,  3.00it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 64%|██████▍   | 61/95 [00:26<00:14,  2.38it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 65%|██████▌   | 62/95 [00:27<00:15,  2.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 66%|██████▋   | 63/95 [00:27<00:15,  2.00it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 67%|██████▋   | 64/95 [00:28<00:14,  2.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 68%|██████▊   | 65/95 [00:28<00:12,  2.33it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 69%|██████▉   | 66/95 [00:28<00:12,  2.40it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 71%|███████   | 67/95 [00:29<00:11,  2.44it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 72%|███████▏  | 68/95 [00:29<00:10,  2.57it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 73%|███████▎  | 69/95 [00:30<00:16,  1.54it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 74%|███████▎  | 70/95 [00:31<00:14,  1.77it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 75%|███████▍  | 71/95 [00:31<00:13,  1.72it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 76%|███████▌  | 72/95 [00:32<00:12,  1.91it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 77%|███████▋  | 73/95 [00:32<00:09,  2.22it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 78%|███████▊  | 74/95 [00:32<00:09,  2.20it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 79%|███████▉  | 75/95 [00:33<00:08,  2.39it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 80%|████████  | 76/95 [00:33<00:07,  2.58it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 81%|████████  | 77/95 [00:34<00:07,  2.49it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 82%|████████▏ | 78/95 [00:34<00:06,  2.48it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 83%|████████▎ | 79/95 [00:35<00:08,  1.99it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 84%|████████▍ | 80/95 [00:35<00:06,  2.30it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 85%|████████▌ | 81/95 [00:35<00:06,  2.32it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 86%|████████▋ | 82/95 [00:36<00:05,  2.39it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 87%|████████▋ | 83/95 [00:36<00:04,  2.47it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 88%|████████▊ | 84/95 [00:37<00:04,  2.48it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 89%|████████▉ | 85/95 [00:37<00:04,  2.38it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 91%|█████████ | 86/95 [00:37<00:03,  2.34it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 92%|█████████▏| 87/95 [00:38<00:03,  2.46it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 93%|█████████▎| 88/95 [00:38<00:02,  2.49it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 94%|█████████▎| 89/95 [00:39<00:02,  2.23it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 95%|█████████▍| 90/95 [00:39<00:02,  2.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 96%|█████████▌| 91/95 [00:40<00:01,  2.27it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 97%|█████████▋| 92/95 [00:40<00:01,  2.31it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 98%|█████████▊| 93/95 [00:40<00:00,  2.52it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 99%|█████████▉| 94/95 [00:41<00:00,  2.87it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
100%|██████████| 95/95 [00:41<00:00,  2.28it/s]

======== atticionic ========
CER  : 82.29%
ACC1 : 8.27%
ACC20: 19.17%
======== doric ========
CER  : 80.37%
ACC1 : 12.50%
ACC20: 22.50%
======== northwest ========
CER  : 91.67%
ACC1 : 0.00%
ACC20: 40.00%
======== aeolic ========
CER  : 87.50%
ACC1 : 0.00%
ACC20: 33.33%
======== TOTAL ========
CER : 84.70%
ACC1 : 6.31%
ACC20 : 17.74%

In [5]:
import json
from transformers import pipeline, AutoTokenizer, LlamaForCausalLM, AutoModelForCausalLM
from accelerate import init_empty_weights, load_checkpoint_and_dispatch
import torch
import warnings
warnings.filterwarnings("ignore", message=".*copying from a non-meta parameter in the checkpoint*")
model_id = "Ericu950/Epigr_3_Llama-3.1-8B-Instruct_text"

with init_empty_weights():
    model = LlamaForCausalLM.from_pretrained(model_id)

model = LlamaForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
    torch_dtype=torch.float16, # Recommended for Llama to save memory
    offload_folder="offload"
)

tokenizer = AutoTokenizer.from_pretrained(model_id)

generation_pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    device_map="auto",
)

ctop1s = []
ctop20s = []

editd = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc1 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}
acc20 = { d: { x: [] for x in range(1, max_l+1)} for d in dialects}

pbar = tqdm(test_set)
for inscription in pbar:
    ground_truth = inscription['masked_gt']
    
    masked = inscription['masked_ag'].replace('[MASK]', f"[{len(ground_truth)} missing letters]" )

    dialect = inscription['dialect']
    
    system_prompt = "Fill in the missing letters in this inscription!"
    input_messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": masked},
    ]
    terminators = [
        tokenizer.eos_token_id,
        tokenizer.convert_tokens_to_ids("<|eot_id|>")
    ]
    outputs = generation_pipeline(
        input_messages,
        max_new_tokens=10,
        num_beams=30, # Set this as high as your memory will allow!
        num_return_sequences=20,
        early_stopping=True,
    )
    constr = []
    for output in outputs:
        generated_text = output.get('generated_text', [])
        for item in generated_text:
            if item.get('role') == 'assistant':
                constr.append(item.get('content'))


    ctop1 = 0
    ctop20 = 0
    if ground_truth in [ x for x in constr[:1] ]:
        ctop1 = 1
        ctop20 = 1
    if ground_truth in [ x for x in constr ]:
        ctop20 = 1

    ctop1s.append(ctop1)
    ctop20s.append(ctop20)
    acc1[dialect][len(ground_truth)].append(ctop1)
    acc20[dialect][len(ground_truth)].append(ctop20)

    if constr != []:
        editd[dialect][len(ground_truth)].append(editdistance.eval(constr[0], ground_truth) / len(ground_truth))
    else:
        editd[dialect][len(ground_truth)].append(1.0)

for dialect in dialects:
    print(f"======== {dialect} ========")
    print(f'CER  : {np.mean([np.mean(v) for v in editd[dialect].values() if v])*100:.2f}%')
    print(f'ACC1 : {np.mean([np.mean(v) for v in acc1[dialect].values() if v])*100:.2f}%')
    print(f'ACC20: {np.mean([np.mean(v) for v in acc20[dialect].values() if v])*100:.2f}%')

print(f"======== TOTAL ========")
cert = { x: [] for x in range(1, max_l+1)}
for k, vs in editd.items():
    for kk, v in vs.items():
        cert[kk].extend(v)
acc1t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc1.items():
    for kk, v in vs.items():
        acc1t[kk].extend(v)

acc20t = { x: [] for x in range(1, max_l+1)}
for k, vs in acc20.items():
    for kk, v in vs.items():
        acc20t[kk].extend(v)
print(f'CER : {np.mean([np.mean(v) for v in cert.values() if v])*100:.2f}%')
print(f'ACC1 : {np.mean([np.mean(v) for v in acc1t.values() if v])*100:.2f}%')
print(f'ACC20 : {np.mean([np.mean(v) for v in acc20t.values() if v])*100:.2f}%')

Loading checkpoint shards: 100%|██████████| 4/4 [00:03<00:00,  1.26it/s]
Loading checkpoint shards: 100%|██████████| 4/4 [00:02<00:00,  1.52it/s]
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Device set to use cuda:0
  0%|          | 0/95 [00:00<?, ?it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 1/95 [00:00<00:55,  1.70it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 2/95 [00:00<00:37,  2.48it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 3/95 [00:01<00:37,  2.43it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▍         | 4/95 [00:01<00:36,  2.50it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  5%|▌         | 5/95 [00:02<00:35,  2.55it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  6%|▋         | 6/95 [00:02<00:34,  2.56it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  7%|▋         | 7/95 [00:02<00:34,  2.56it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  8%|▊         | 8/95 [00:03<00:32,  2.66it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  9%|▉         | 9/95 [00:03<00:33,  2.57it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 11%|█         | 10/95 [00:03<00:32,  2.64it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 12%|█▏        | 11/95 [00:04<00:35,  2.38it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 13%|█▎        | 12/95 [00:04<00:37,  2.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 14%|█▎        | 13/95 [00:05<00:35,  2.30it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 15%|█▍        | 14/95 [00:05<00:33,  2.44it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 16%|█▌        | 15/95 [00:06<00:29,  2.70it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 17%|█▋        | 16/95 [00:06<00:32,  2.44it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 18%|█▊        | 17/95 [00:06<00:28,  2.71it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 19%|█▉        | 18/95 [00:07<00:27,  2.76it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 20%|██        | 19/95 [00:07<00:28,  2.67it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 21%|██        | 20/95 [00:08<00:30,  2.46it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 22%|██▏       | 21/95 [00:08<00:33,  2.20it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 23%|██▎       | 22/95 [00:09<00:33,  2.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 24%|██▍       | 23/95 [00:09<00:32,  2.23it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 25%|██▌       | 24/95 [00:09<00:29,  2.39it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 26%|██▋       | 25/95 [00:10<00:27,  2.54it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 27%|██▋       | 26/95 [00:10<00:26,  2.62it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 28%|██▊       | 27/95 [00:10<00:25,  2.68it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 29%|██▉       | 28/95 [00:11<00:26,  2.52it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 31%|███       | 29/95 [00:11<00:25,  2.54it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 32%|███▏      | 30/95 [00:12<00:28,  2.28it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 33%|███▎      | 31/95 [00:12<00:25,  2.53it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 34%|███▎      | 32/95 [00:12<00:25,  2.48it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 35%|███▍      | 33/95 [00:13<00:26,  2.38it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 36%|███▌      | 34/95 [00:13<00:23,  2.65it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 37%|███▋      | 35/95 [00:14<00:22,  2.63it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 38%|███▊      | 36/95 [00:14<00:22,  2.58it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 39%|███▉      | 37/95 [00:15<00:26,  2.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 40%|████      | 38/95 [00:15<00:23,  2.43it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 41%|████      | 39/95 [00:15<00:20,  2.69it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 42%|████▏     | 40/95 [00:16<00:30,  1.82it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 43%|████▎     | 41/95 [00:17<00:26,  2.01it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 44%|████▍     | 42/95 [00:17<00:25,  2.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 45%|████▌     | 43/95 [00:17<00:25,  2.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 46%|████▋     | 44/95 [00:18<00:21,  2.36it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 47%|████▋     | 45/95 [00:18<00:20,  2.42it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 48%|████▊     | 46/95 [00:19<00:19,  2.49it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 49%|████▉     | 47/95 [00:19<00:20,  2.31it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 51%|█████     | 48/95 [00:19<00:19,  2.38it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 52%|█████▏    | 49/95 [00:20<00:19,  2.37it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 53%|█████▎    | 50/95 [00:20<00:17,  2.52it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 54%|█████▎    | 51/95 [00:21<00:17,  2.56it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 55%|█████▍    | 52/95 [00:21<00:16,  2.61it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 56%|█████▌    | 53/95 [00:22<00:18,  2.22it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 57%|█████▋    | 54/95 [00:22<00:17,  2.41it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 58%|█████▊    | 55/95 [00:22<00:16,  2.46it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 59%|█████▉    | 56/95 [00:23<00:16,  2.33it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 60%|██████    | 57/95 [00:23<00:16,  2.35it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 61%|██████    | 58/95 [00:23<00:14,  2.53it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 62%|██████▏   | 59/95 [00:24<00:12,  2.79it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 63%|██████▎   | 60/95 [00:24<00:11,  3.02it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 64%|██████▍   | 61/95 [00:25<00:14,  2.38it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 65%|██████▌   | 62/95 [00:25<00:15,  2.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 66%|██████▋   | 63/95 [00:26<00:15,  2.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 67%|██████▋   | 64/95 [00:26<00:14,  2.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 68%|██████▊   | 65/95 [00:26<00:12,  2.40it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 69%|██████▉   | 66/95 [00:27<00:11,  2.44it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 71%|███████   | 67/95 [00:27<00:11,  2.40it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 72%|███████▏  | 68/95 [00:28<00:10,  2.54it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 73%|███████▎  | 69/95 [00:29<00:15,  1.64it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 74%|███████▎  | 70/95 [00:29<00:13,  1.86it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 75%|███████▍  | 71/95 [00:30<00:13,  1.77it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 76%|███████▌  | 72/95 [00:30<00:12,  1.91it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 77%|███████▋  | 73/95 [00:30<00:10,  2.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 78%|███████▊  | 74/95 [00:31<00:09,  2.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 79%|███████▉  | 75/95 [00:31<00:08,  2.35it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 80%|████████  | 76/95 [00:32<00:07,  2.54it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 81%|████████  | 77/95 [00:32<00:07,  2.54it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 82%|████████▏ | 78/95 [00:32<00:06,  2.51it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 83%|████████▎ | 79/95 [00:33<00:08,  1.95it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 84%|████████▍ | 80/95 [00:33<00:06,  2.31it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 85%|████████▌ | 81/95 [00:34<00:05,  2.38it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 86%|████████▋ | 82/95 [00:34<00:05,  2.36it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 87%|████████▋ | 83/95 [00:35<00:04,  2.51it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 88%|████████▊ | 84/95 [00:35<00:04,  2.53it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 89%|████████▉ | 85/95 [00:35<00:04,  2.47it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 91%|█████████ | 86/95 [00:36<00:03,  2.47it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 92%|█████████▏| 87/95 [00:36<00:03,  2.55it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 93%|█████████▎| 88/95 [00:37<00:02,  2.55it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 94%|█████████▎| 89/95 [00:37<00:02,  2.32it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 95%|█████████▍| 90/95 [00:38<00:02,  2.24it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 96%|█████████▌| 91/95 [00:38<00:01,  2.35it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 97%|█████████▋| 92/95 [00:38<00:01,  2.35it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 98%|█████████▊| 93/95 [00:39<00:00,  2.55it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 99%|█████████▉| 94/95 [00:39<00:00,  2.80it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
100%|██████████| 95/95 [00:39<00:00,  2.38it/s]

======== atticionic ========
CER  : 38.90%
ACC1 : 44.69%
ACC20: 59.15%
======== doric ========
CER  : 62.99%
ACC1 : 27.50%
ACC20: 47.50%
======== northwest ========
CER  : 61.67%
ACC1 : 30.00%
ACC20: 50.00%
======== aeolic ========
CER  : 60.00%
ACC1 : 33.33%
ACC20: 33.33%
======== TOTAL ========
CER : 49.09%
ACC1 : 37.80%
ACC20 : 52.94%